### ISSUE TITLE
Wiki: Client ID not working + solution

### ISSUE THREAD

**Issue by dreimer1986** [keatontaylor/alexa-actions#1]
You are telling to use https://pitangui.amazon.com/ all the time as Client ID

Not entirely true tbh. There are three servers and they are country specific. I as german had to use https://layla.amazon.com/

Here the list:
https://pitangui.amazon.com/ if you are in US
https://layla.amazon.com/ if you are in EU
https://alexa.amazon.co.jp/ if you are in JP and AU

Comes from Home Assistant (https://www.home-assistant.io/integrations/alexa.smart_home/)

**Comment by somar05** [comment]
Good point. Thanks @dreimer1986 . Now I can achieve the login request for HA instance, but something is avoiding finish the login process. It looks a time out. Under investigation...

**Comment by dreimer1986** [comment]
For me the account linking worked fine then. My germanized default test text is coming as reply, too.

**Comment by mgiako** [comment]
I can't finish the login process too, maybe we must use port 443 as reported here: https://www.home-assistant.io/integrations/alexa.smart_home/#account-linking
I use port 8123 but it's ssl anyway

**Comment by dreimer1986** [comment]
I use 443 for ages now. So, maybe

**Comment by mgiako** [comment]
Understood! But I use also haaska ant that's working perfectly with port 8123. Hope that @keatontaylor can answer me on this.

**Comment by somar05** [comment]
Same case for me: ssl mapped to different port, but working fine with haaska.

**Comment by AngelofromTurin** [comment]
> I can't finish the login process too, maybe we must use port 443 as reported here: https://www.home-assistant.io/integrations/alexa.smart_home/#account-linking
> I use port 8123 but it's ssl anyway
> 
> By the way, I'm using https://layla.amazon.com/ because I'm in Italy, Got invalid url if using pitangui

same situation

**Comment by keatontaylor** [comment]
@mgiako amazon requires account linking be done on port 443. If you need to avoid that. You can turn off account linking and hardcode self.token in lambda_function.py with a long lived token you generate in your home assistant installation.

**Comment by keatontaylor** [comment]
I’ve updated the wiki as well to add these use cases.

**Comment by mgiako** [comment]
thanks! I'll try

**Comment by mgiako** [comment]
Ok, this is working! 
If you don't want to use 443 port. You can generate a long lived token an put this on line 27:
`self.token = 'your long lived token'`
Thanks @keatontaylor

**Comment by keatontaylor** [comment]
Updated the wiki closing this issue for now.
