### ISSUE TITLE
Not asked for account linking

### ISSUE THREAD

**Issue by Morenus77** [keatontaylor/alexa-actions#105]
Hi to everyone and thanks for this add-on.
I configured the skill as described, skipping the account linking steps since I'm using duckdns with the 8123 port.
I valued the long live token attribute, but when I enable the skill It doesn't ask me to login to my account.
The 'account required' notification appears only if I follow the account linking steps, but obviously It doesn't work.
Anyone had the same issue? How to solve it? Thanks in advance

**Comment by calcioscacchi** [comment]
@Morenus77 I have the same problem. The issue is that if we enable the first option, we MUST set the URIs. But, as explained in the wiki, we have to skip all the account linking step.

**Comment by calcioscacchi** [comment]
I just solve that setting the long live token (generated in home assistant) in the lambda_function.py.
You have to paste the token between the double quotes.
