### ISSUE TITLE
Authentication Error to HA leads to Error in Lambda.py

### ISSUE THREAD

**Issue by StephaneM60** [keatontaylor/alexa-actions#106]
Hi,

I'm using actionnable notification for quite some time and I'm facing a small issue.

At times, the skill cannot authenticate with Home Assistant. I'm using account linking and I can see tha Home Assistant is complaining about authentication when the skill tries to login :

`WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ec2-34-245-166-43.eu-west-1.compute.amazonaws.com (34.245.166.43). (None)`

So I'll have to figure out why sometimes it works, why at other times it don't (and when it works, it works well even with response made to Alexa)

However, when this happens, Alexa complains with a generic error message : there is a problem with the skill response (in French). If I review the AWS log, I can see this : 

`TypeError: not all arguments converted during string formatting`

This happens when trying to format the error message from : logger.error("401 Error", response.data) as revealed by the stack trace

```
Traceback (most recent call last):
  File "/var/task/ask_sdk_core/skill_builder.py", line 111, in wrapper
    request_envelope=request_envelope, context=context)
  File "/var/task/ask_sdk_core/skill.py", line 207, in invoke
    handler_input=handler_input)
  File "/var/task/ask_sdk_runtime/dispatch.py", line 131, in dispatch
    return exception_handler.handle(handler_input, e)
  File "/var/task/lambda_function.py", line 358, in handle
    home_assistant_object = HomeAssistant()
  File "/var/task/lambda_function.py", line 57, in __init__
    self.get_ha_state()
  File "/var/task/lambda_function.py", line 99, in get_ha_state
    errors = self._check_response_errors(response)
  File "/var/task/lambda_function.py", line 68, in _check_response_errors
    logger.error("401 Error", response.data)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/var/runtime/bootstrap.py", line 239, in emit
    msg = self.format(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/var/lang/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
```

The only thing that may be of influence is that I'm using this skill in French...

**Comment by DEADSEC-SECURITY** [comment]
Did you add support to French? Did you try a long living access token hard coded?

**Comment by StephaneM60** [comment]
Yes I added support for French language.

I'm using an long living access token (without the token, sometimes HA was rejecting the authentication), though I can't remember if I started to use the token to suppress the issue or if the issue still exists with the token (it has been a long time now that it works without failure)

Though my point was that the skill was crashing on the logger.error("401 Error", response.data)

This is what I added to language_strings.json :

`"fr": {
	     "ERROR_401": "Il me semble que je ne suis pas autorisé à accéder à Home Assistant, merci de vérifier votre association de compte ou votre token permanent et essayer à nouveau",
		"ERROR_404": "Il me semble que je ne peux pas trouver une entité de saisie de texte. Merci de vérifier que vous avez ajouté cette entité et essayer à nouveau",
		"ERROR_400": "Impossible de communiquer avec Home Assistant. Merci de vérifier les journaux Amazon CloudWatch dans la console de développeur Amazon pour votre skill.",
	    "ERROR_ACOUSTIC": "Désolé je ne comprends pas... <break time='200ms'/> {}",
		"ERROR_CONFIG": "Désolé, je recontre des difficultés, merci de vérifier la configuration de votre skill et essayer à nouveau.",
		"ERROR_SPECIFIC_DATE": "Désolé, je ne peux pas encore programmer une date précise, essayez une durée plutôt, comme... dans 5 heures",
		"HELP_MESSAGE": "Cette skill ne devrait être déclenchée que par Home Assistant.",
		"OKAY": "Ok",
		"SKILL_NAME": "Actions Personnalisées Home Assistant",
		"STOP_MESSAGE": "Au revoir !",
		"SELECTED" : "Vous avez sélectionné {}",
		"WELCOME_MESSAGE": "Bienvenue dans {}. Le texte saisi est: {}"
	}`

**Comment by DEADSEC-SECURITY** [comment]
Did it work before? Did you update Home Assistant recently?

**Comment by StephaneM60** [comment]
Well as it has been a long time since I posted the report I can't remember exactly if the issue only existed before I used the long lived token.

Though when I was having failure to authenticate : it was working but not 100% of the time. So a the root of it, the issue is Home Assistant is rejecting the authentication from the skill, that's fine for me, what is not fine regarding the skill : is that the error message supposed to be played by the echo (the 401 error) isn't played at all because the skill is crashing.

So the crashing skill part has nothing to do with HA at all, its all contained on the Amazon part of the skill.

And yes I'm updating HA whenever a new version is out, so it is always up to date (as well as any thing HA related)

My knowledge of skill development is very limited so I can't see immediately why the skill crash with the error "TypeError: not all arguments converted during string formatting" when the skill is obviously sending the error message for the authentication issue to be played back by the Echo.

By the way : other than that the skill is working, and is using the right language (well it says "Ok" when we are responding back... so it is the same thing as in other languages, but it says "Ok" and not erroring out...)

**Comment by StephaneM60** [comment]
The input text entity ? Yes it has a initial value.

I see that you updated the code for the logger.error, so when you ask me to re-make the skill, you mean with the updated code?

I will but I'll probably never have the issue again now that I use the token.

**Comment by DEADSEC-SECURITY** [comment]
If the issue is fixed don't worry about. Alexa has some instabilities with Nabu Casa, as reported by other users so if the Token fixed the issue it was probably a bug with alexa auth.
