### ISSUE TITLE
Actionable Notifications not working on Amazon Flex

### ISSUE THREAD

**Issue by rhysypoos** [keatontaylor/alexa-actions#107]
I have Alexa Actionable Notifications all set up and working well, except when I try and trigger it through an Amazon Flex device. 

It works fine with an Echo Input too, but I've noticed that Echo Input entity IDs in Home Assistant report as media_player.deviceName_echo, just like a regular Echo, whereas the Flex has an ID of media_player.deviceName_flex, so I'm wondering if that's part of the issue and whether there's a workaround for this?

Thanks.

**Comment by DEADSEC-SECURITY** [comment]
I don't have a Amazon Flex but are you able to play media via the home assistant service dev tools to that device? Maybe this is not a bug for this repo but for the media player.
