### ISSUE TITLE
Feature: Support for Alexa Speaker Groups

### ISSUE THREAD

**Issue by that1guy** [keatontaylor/alexa-actions#118]
Awesome implementation so far!  Using this with Node Red + Home Assistant is magical.

Feature Request: Send an actionable notification to an Alexa Speaker Group.  Process the first response heard from any Alexas in the group, else callback with no response.

Example announcement:  "It's looks like the home is empty.  Is anyone here?".
Example action if anyone responded: "Oops, I won't turn the home off then."
Example action if nobody responds: "Turning off the home."

FYI - These Alexa Speaker groups appear in Home Assistant as: `media_player.<name_of_group>`.  

I know we can achieve this with a complex Node-Red flow, but I'm hoping we can have a more elegant, scalable solution here.

**Comment by DEADSEC-SECURITY** [comment]
Could you confirm you tried to run the skill with a group instead of a device?

**Comment by that1guy** [comment]
Yes.  

When I call the alexa skill & point to an Alexa group I hear all the Echos chime, but no TTS response, and therefore no way to respond to the skill.
