### ISSUE TITLE
Feature Request - Ask for Duration/Time

### ISSUE THREAD

**Issue by stevenjev** [keatontaylor/alexa-actions#12]
I apologize if this is not the correct method to do this. However, I been using this code and its been great! 

I really wanted to have Alexa ask me for a time (e.g. Q: How long would you like the fan on?) and wait for a response (e.g. A: 20 minutes). I figured out how to do that using your code as a base and added a new custom intent to listen for a duration. I've [forked](https://github.com/stevenjev/alexa-actions) the project with the necessary code modifications and screenshot of the required Custom Intent. 

I'm sure you've already figured out how to do this, but I thought I would see if you'd be interested in adding it to this project. The biggest downside I see is that it would require the end user to create a Custom Intent (which is a few more steps + added complication).

Thanks again for providing this!

**Comment by keatontaylor** [comment]
@stevenjev I was just about to update the code to add generic selections of text, but the time based slot sounds fantastic too.

[Advanced Features](https://github.com/keatontaylor/alexa-actions/wiki/AdvancedFeatures) is where I want to put all this additional stuff beyond the basic config, but feel free to make a merge request to add it into the lambda_function.py code so it is ready for those who want to take the extra leap.

**Comment by stevenjev** [comment]
@keatontaylor The Advanced Features section is a great idea to separate features, as it looks like there's a lot of potential for this. My level of skill when it comes to writing this is pretty basic. While I did get it working, I may hold off on merging - just wanted to let you know! Feel free to use it however.
