### ISSUE TITLE
ResponseSelection should be ResponseSelect

### ISSUE THREAD

**Issue by lorenzocas** [keatontaylor/alexa-actions#120]
Thanks for the great tutorial. 
Just a small problem in the documentation for the various kind of event_response_types.
They're all right except ResponseSelection, it's not valid. Looking at the code it should be "ResponseSelect"

**Comment by DEADSEC-SECURITY** [comment]
Would you mind opening a pull request with the proposed change?

**Comment by lorenzocas** [comment]
I'm not sure how to do this. I think this should be fixed on the tutorial post and not on the code itself.
