### ISSUE TITLE
Help with ResponseSelection

### ISSUE THREAD

**Issue by itsboo07** [keatontaylor/alexa-actions#122]
hi, firstly thanks for this great project. 
im trying to run  the bellow command under ( `service: script.activate_alexa_actionable_notification` ) but it fails to call out and alexa responds, their was a problem with the requested skills response. if i try regular texts it works.
if i run the same below code with service: notify_alexa_media_mydevice_ then it works.  any fix around?
`"<amazon:effect name="whispered">The front door has been unlocked for 5 mins, would you like me to lock it?</amazon:effect>"`

**Comment by DEADSEC-SECURITY** [comment]
Can you send me the full code for the script and whats running it?

**Comment by itsboo07** [comment]
"whispered" this is what was stopping..it supposed to be 'whispered'.
and loveing this project, great respect.
need one help, 
i could run this below code in ha services and it works but if i run the same in node red it fails and says api error or wrong entity..any fix?
`service: script.activate_alexa_actionable_notification
data:
  text: do you want to say something?
  event_id: alexa_notification_media_tv_select
  alexa_device: "{{ states('sensor.last_alexa') }}"`

node red code:
`
{
    "text": "what to search",
    "event_id": "actionable_notification_tv_search",
    "alexa_device": "{{states('sensor.last_alexa')}}"
}`

**Comment by DEADSEC-SECURITY** [comment]
Great!
