### ISSUE TITLE
Issue with ResponseNone and TuneIn playing on Alexa

### ISSUE THREAD

**Issue by stefanraduionescu** [keatontaylor/alexa-actions#127]
If an Alexa device is playing TuneIn or Spotify music.
The device I am using it is an echo Show 8.

After the question from actionable notification comes, for example one question and I give no response -  ResponseNone comes, music remains at a lower volume until the next voice request for alexa. Then it returns to original state.
I tested with responseNo and responseYes, the music returns to the original volume after the answer. I think something hangs on the skill waiting for the answer.
For this question i used only ResponseYes automation.

**Comment by DEADSEC-SECURITY** [comment]
Echo devices are not supported yet

**Comment by DEADSEC-SECURITY** [comment]
This should be fixed with new branch mods. Please test as I'm not sure about Echo Show devices
