### ISSUE TITLE
Need a little help

### ISSUE THREAD

**Issue by rlust** [keatontaylor/alexa-actions#13]
Great work here!
I am missing how to do this step

Copy and paste the code from the lambda_function.py in this repo into the lambda_function.py file in the skill code developer console.

No sure where to copy the code.

**Comment by keatontaylor** [comment]
Under `Code` in the Alexa Developer Console, replace all the code in the` lambda_function.py` with the code in this repo. 

Steven also made an excellent tutorial [here](https://discordapp.com/channels/469330414121517056/469338084765335562/708478344429043805)

**Comment by rlust** [comment]
Thanks much! Some times word I read do not sink in :)

Well done!

**Comment by keatontaylor** [comment]
Going to close the issue if you're up and running :)
