### ISSUE TITLE
Folder structure differs - direct git import not possible

### ISSUE THREAD

**Issue by elmar-hinz** [keatontaylor/alexa-actions#132]
The the folders differ between the repo and the alexa developer console, at least for the position of `requirements.txt`.

<img width="237" alt="Screenshot 2022-12-21 at 18 40 33" src="https://user-images.githubusercontent.com/1227339/208969606-ae68c2bd-1147-4af8-bdda-6d9d9cdac342.png">

![Screenshot 2022-12-21 at 18 39 44](https://user-images.githubusercontent.com/1227339/208969898-e7db5895-de40-4328-b92b-bd3cc16fdce9.png)

This may explain, why a direct import of the repo is not possible.

![Screenshot 2022-12-21 at 18 47 48](https://user-images.githubusercontent.com/1227339/208971068-55962a2c-4cde-485d-bea6-f4f388c6b494.png)

![Screenshot 2022-12-21 at 18 48 06](https://user-images.githubusercontent.com/1227339/208971088-8d617459-6f8d-4560-a60a-fa6319e99e94.png)

**Comment by elmar-hinz** [comment]
One of the best parts of home assistant. Maybe some contributions new and then. I consider the same concept based on node.js, independent of the media player and triggered by the hue bridge.

**Comment by elmar-hinz** [comment]
Looking for the documentation. This is a relevant part for [importing](https://developer.amazon.com/en-US/docs/alexa/hosted-skills/alexa-hosted-skills-git-import.html#structure).

![Screenshot 2022-12-25 at 11 06 02](https://user-images.githubusercontent.com/1227339/209463907-75cda080-03bb-496e-9787-36f7a98f4f85.png)

**Comment by DEADSEC-SECURITY** [comment]
This is fixed.
