### ISSUE TITLE
Interactive Notification Does Not Initiate On Its Own

### ISSUE THREAD

**Issue by briancbusch** [keatontaylor/alexa-actions#138]
I have seen a few reports of people setting this up and having an issue. The notification does not start on its own. It requires me to say "Alexa, open custom actions" and only then do I get the notification. I'm not sure if this is a new settings problem with new installs or if this is an install error. I followed the instructions in the wiki and also the YouTube video from Mark Watt Tech, so I don't think I did anything on the install to force the problem. I want to make sure that the instructions are right as I can tell Amazon has changed the console and the process just slightly from when this was originally written. Happy to help however I can, but I don't know how to troubleshoot this one.

**Comment by elmar-hinz** [comment]
If "Alexa, open custom actions" does answer, the configuration is working at least half the way. The skill is connecting to the REST Api of your HA. That's fine.

1. Check that you have created and deployed a BUILD for the language your echo. I don't think it will work, if you import "en-US" when your devices are configured to a different language.

2. Check you have setup `scripts.yaml` properly with your personal skill id, something like:

```  media_content_id: amzn1.ask.skill.a59e61c1-d917-425d-9b03-xxxxxxxxxx ```

3. Mind to restart HA to read the configurations.

I you use node red, you may setup a test like this one.

![Screenshot 2022-12-29 at 10 10 50](https://user-images.githubusercontent.com/1227339/209929564-ea37dd22-3f5f-4de2-b395-2ee23e1a95a1.png)

**Comment by DEADSEC-SECURITY** [comment]
I'm making this comment the issue template @elmar-hinz.

**Comment by briancbusch** [comment]
It appears the issue is related to Amazon accounts. I built the skill in my account but attempted to send the notification to an Echo device registered under my wife's account. When I attempted to send it to an Echo device registered on my account, it worked just fine. I would recommend adding that note to the setup.

**Comment by elmar-hinz** [comment]
@briancbusch Thank you for solving it.I added a notices here: 

https://github.com/keatontaylor/alexa-actions/wiki/Prerequisites

Does it catch the situation?

**Comment by DEADSEC-SECURITY** [comment]
![image](https://user-images.githubusercontent.com/45077772/210226267-bae6ab8f-340f-4c56-bf48-8696a77defd3.png)
I just cracked laughing when I read this.

**Comment by elmar-hinz** [comment]
And they still call this stupid devices smart. What is Amazon doing with all those billions?

**Comment by briancbusch** [comment]
> @briancbusch Thank you for solving it.I added a notices here:
> 
> https://github.com/keatontaylor/alexa-actions/wiki/Prerequisites
> 
> Does it catch the situation?

Yes, that should work! Hopefully prevents the confusion in the future. Thanks!

**Comment by briancbusch** [comment]
> ![image](https://user-images.githubusercontent.com/45077772/210226267-bae6ab8f-340f-4c56-bf48-8696a77defd3.png) I just cracked laughing when I read this.

It was hard to sift through it because in my account, I can see and interact with all my wife's registered devices in the Alexa phone app. It didn't occur to me until I was deep into troubleshooting that it might be an account link problem. In the end, I'm just glad it's sorted and it's working.

**Comment by elmar-hinz** [comment]
> It was hard to sift through it because in my account, I can see and interact with all my wife's registered devices in the Alexa phone app. It didn't occur to me until I was deep into troubleshooting that it might be an account link problem. In the end, I'm just glad it's sorted and it's working.

It's indeed not just a funny human assumption, that one could reach all devices of the home. They are all connected to Home Assistant and HA suggests them during scripting, independent from the Amazon account. 

One should be able to address this by improving the code, if Home Assistant is tracking the different Amazon accounts. It's likely there is some information one could utilise to throw a warning.

**Comment by DEADSEC-SECURITY** [comment]
You could fix this @briancbusch by creating amazon sub accounts instead of new accounts.

If you use sub accounts it fixes your issue but your wife would have to use your account as the main one
