### ISSUE TITLE
Please review the new wiki pages

### ISSUE THREAD

**Issue by elmar-hinz** [keatontaylor/alexa-actions#141]
The page of the skill import has been fully rewritten. Hitherto it was manually copying a lot of files. Now it is a matter of clicking a button. Please review the page before I exchange the old page against the new one.

* https://github.com/keatontaylor/alexa-actions/wiki/Importing-the-skill

There are another two pages, that are new. They basically hold the old information, just organised differently. They are already connected.

* https://github.com/keatontaylor/alexa-actions/wiki/Prerequisites
* https://github.com/keatontaylor/alexa-actions/wiki/Initial-Home-Assistant-Config

**Comment by DEADSEC-SECURITY** [comment]
Yhe I like it

**Comment by DEADSEC-SECURITY** [comment]
Thanks for the contribution
