### ISSUE TITLE
Script for the ResponseSelect action

### ISSUE THREAD

**Issue by flow1990** [keatontaylor/alexa-actions#144]
Hey, is it possible to see the script for the option if alexa gets an select input as answer? I am trying and trying but can not get it tot work...

thanks

**Comment by DEADSEC-SECURITY** [comment]
Is this what you want? 
https://github.com/keatontaylor/alexa-actions/blob/4def48ebe2cc0e1cdcba138dd30150c12d34de59/skill-package/interactionModels/custom/en-US.json

**Comment by flow1990** [comment]
No I mean for the „ media_player.select_source“ you are using in the Advanced example. Isn‘t this a script?

**Comment by DEADSEC-SECURITY** [comment]
@flow1990

**Comment by flow1990** [comment]
Where is „media_player.select_source“
coming from?

**Comment by DEADSEC-SECURITY** [comment]
Where do you see that?
@flow1990 
Dude for me to be able to help you, you need to explain things not ask stuff with no context. I wish I could read minds but I cant yet so please explain stuff properly.

**Comment by flow1990** [comment]
I am sorry for me this was clear. In the Wiki in the „Advanced festures“ section in the last example where „AnswerSelect“ is explanined. You use 
- alias: TV turned on and user wants Netflix
    trigger:
      platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: alexa_notification_media_tv_select
    action:
      - service: media_player.select_source
        entity_id: media_player.tv
        data_template:
          source: "{{ trigger.event.data.event_response }}"

as I understand it there is a Script called „media_player.select_source“ and I would love to see this script.

**Comment by DEADSEC-SECURITY** [comment]
Thats not a script. Thats the media_player integration you need from HACS.

select_source is just a placeholder for the actual value you need.

Check this part of the wiki and let me know if it fixes your issue
https://github.com/keatontaylor/alexa-actions/wiki/Home-Assistant-Talking-to-Alexa-(The-Script)

**Comment by flow1990** [comment]
- alias: Daily Briefing_Antwort Select
  trigger:
    platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_office_good_morning
  action:
    - service: notify.alexa_media_echo_dot_buro
      data:
        message: "{{ trigger.event.data.event_response }}"   
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean."{{ trigger.event.data.event_response }}"  
        
This is how I try it, to test if alexa got the selection right I let her say what I said to her in the first action, this works. The second action "input_boolean.turn_on" is not working. I have a slot value in the developer console which is called "wetter" and an "input_boolean.wetter". Am I missing something?

BTW thank you so much for your help and patience!
