### ISSUE TITLE
My part of the Wiki done so far, please review the mistakes

### ISSUE THREAD

**Issue by elmar-hinz** [keatontaylor/alexa-actions#145]
You may have observed, I did a lot of edits in the wiki.  I tried to follow the concept of Keaton, to do a step by step setup. At the bottom of each page there is a uniform link to the next step.  I also tried to get some structure into the pages.

* goals of the step
* prerequisites
* installation
* configuration
* success checking
* next

Not all pages contain all topics. I set a focus upon success checking. So the reader doesn't have to wait until the last step to figure out, if matters go wrong.

IMPORTANT: I did work on all pages from **Home** down to **Hello World.** I did not work upon **Examples** and **Advanced topics** at all. My experience and goals end with **Hello World**.

I guess I created a lot of typos and mistakes in punctuation. I am no native speaker. Would be cool to have some native speaker to review that kind of stuff.

 A little part remains for me to do, though, **Hello World** with **Node Red**.

**Comment by DEADSEC-SECURITY** [comment]
Ill do the spell checking dont worry
