### ISSUE TITLE
Adding a testing framework

### ISSUE THREAD

**Issue by elmar-hinz** [keatontaylor/alexa-actions#155]
I suggest to install one (and later maybe more) frameworks for testing. There are multiple levels to consider on the long run.

- unit testing: testing single small units, typically a singe method.
- integration testing: testing the interactions of multiple components
- acceptance testing: testing the real system end-to-end 

At least the third class does require real connections to the outside world and is most difficult to set up. Better starting at the other end.

Any preferences to the testing framework? 

Python has unit testing built in as `unittest`: https://docs.python.org/3/library/unittest.html

pro:

* less dependencies

cons: 

* outdated xUnit style compared to BDD

Full overview of testing tools: https://wiki.python.org/moin/PythonTestingToolsTaxonomy (last updated in 2020)

**Comment by DEADSEC-SECURITY** [comment]
Its a bit harder to test the skills cuz most of the stuff are alexa callable classes and functions so our coverage wont be that good ayway

**Comment by elmar-hinz** [comment]
That's were stubbing and mocking enter the game, to decouple testing from the outer world. Once decoupled, you get a sound and flexible architecture as a side effect.

For javascript there is even [virtual alexa](https://www.npmjs.com/package/virtual-alexa). In python I didn't find anything comparable, though.
