### ISSUE TITLE
Which version of Python is the skill using?

### ISSUE THREAD

**Issue by elmar-hinz** [keatontaylor/alexa-actions#156]
This ticket is only created for the purpose, to get the information about version detection into the issue database.

To support development people need to know the version of the python environment. 

* What is the docs telling? 
* How to figure out realtime in the developer console?

**Comment by elmar-hinz** [comment]
The docs currently say 3.7. [Source](https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#considerations)

<img width="553" alt="Screenshot 2023-01-08 at 10 44 04" src="https://user-images.githubusercontent.com/1227339/211189842-9be890f0-8e23-422b-a836-1bc4fb1f457c.png">

**Comment by DEADSEC-SECURITY** [comment]
Using setup.py is a good option, we could also put this under the CONTRIBUTING.md.

**Comment by DEADSEC-SECURITY** [comment]
Duplicate of #157
