### ISSUE TITLE
How to inform the developer of the required python version?

### ISSUE THREAD

**Issue by elmar-hinz** [keatontaylor/alexa-actions#157]
The version provided by Amazon is always some years behind. The current version 3.7 dates back to 2018. 

Should there be a `setup.py` or similar to enforce the old version?

**Comment by DEADSEC-SECURITY** [comment]
Well if docs say python37 then we should try to limit to python37 otherwise some errors may occur that are hard to debug.

**Comment by elmar-hinz** [comment]
I am not that much in the recent python technologies. `setup.py` sounds familiar. This discussion from 2018 (already 5 yrs) suggests two different approaches:

https://stackoverflow.com/questions/19534896/enforcing-python-version-in-setup-py
