### ISSUE TITLE
[Bug]: French/CA working with French/FR ?

### ISSUE THREAD

**Issue by MrDrew514** [keatontaylor/alexa-actions#159]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

andrewberniergoupil@gmail.com

### What happened?

I've been trying a few scenarios to make this work but without success so I'll explain my issue. My Alexa setup is French/Canada which is not available in the laguage list but French/FR (France) is there. So I gave FR/fr a try. Under that setup, I'm getting some Utterance Conflicts but I still continued the setup. The testing step was working in the develpper console. Configured the server ip and the token. Once I created the script and edited the skill id's, I couldn't listen to the event when executing the script even tho my media_player was correct nor I couldn't get the alexa echo to speak. So I deleted the skill and started everything again, this time selecting the English/US. Test was sucessful, edited the skill id, but once again I couldn't listen to the event when launching the script. Event was only triggered when testing in the developper console (US language) but nothing using the script and no sound was coming out of the echodot. So I'm really wondering what could be wrong ? Is it because my general setup is French/CA?

### Version

last

### What Alexa device are you using?

Echo

**Comment by DEADSEC-SECURITY** [comment]
What is your alexa default language? @MrDrew514

**Comment by DEADSEC-SECURITY** [comment]
Also please post the logs from cloudwatch so i can better help you figure this out

**Comment by MrDrew514** [comment]
The default language is set to French/Canada, CA/fr, I'll post the logs in a few mins

**Comment by DEADSEC-SECURITY** [comment]
On the code editor in the top menu you can see cloudwatch logs, click it and it should take you to the logs.

**Comment by MrDrew514** [comment]
So what happens is I'm able to get the text from the script (once executed in home assistant) on the 'Test' tab using the words 'actionable notifications', but the echodot speaker is not speaking.

In the Developer Tools > EVENTS, the event alexa_actionable_notification is not triggered when executing the script but it is using the words inside the 'Test' tab.

![image](https://user-images.githubusercontent.com/82120740/211862504-45de178f-0340-442a-a00b-3a2e7d763e90.png)

Not error or warnings in the home assistant logs

Here are the cloudwatch logs:

```
START RequestId: e236349a-5152-45d7-8068-5db616964036 Version: 4
--
Locale is en
[INFO]	2023-01-11T16:17:46.911Z	e236349a-5152-45d7-8068-5db616964036	Locale is en
Session Ended Request Handler triggered
[INFO]	2023-01-11T16:17:46.913Z	e236349a-5152-45d7-8068-5db616964036	Session Ended Request Handler triggered
END RequestId: e236349a-5152-45d7-8068-5db616964036
REPORT RequestId: e236349a-5152-45d7-8068-5db616964036	Duration: 364.26 ms	Billed Duration: 365 ms	Memory Size: 512 MB	Max Memory Used: 49 MB	Init Duration: 308.07 ms
START RequestId: bb0919aa-035e-45cc-8e11-be949a0437a5 Version: 4
Locale is en
[INFO]	2023-01-11T16:17:47.297Z	bb0919aa-035e-45cc-8e11-be949a0437a5	Locale is en
END RequestId: bb0919aa-035e-45cc-8e11-be949a0437a5
REPORT RequestId: bb0919aa-035e-45cc-8e11-be949a0437a5	Duration: 140.52 ms	Billed Duration: 141 ms	Memory Size: 512 MB	Max Memory Used: 50 MB
START RequestId: 63db2b52-4792-49bd-8368-f158eacc949f Version: 4
Locale is en
[INFO]	2023-01-11T16:22:10.444Z	63db2b52-4792-49bd-8368-f158eacc949f	Locale is en
Session Ended Request Handler triggered
[INFO]	2023-01-11T16:22:10.444Z	63db2b52-4792-49bd-8368-f158eacc949f	Session Ended Request Handler triggered
END RequestId: 63db2b52-4792-49bd-8368-f158eacc949f
REPORT RequestId: 63db2b52-4792-49bd-8368-f158eacc949f	Duration: 251.32 ms	Billed Duration: 252 ms	Memory Size: 512 MB	Max Memory Used: 50 MB
START RequestId: cb0957dd-20de-4865-81da-1e267db14462 Version: 4
Locale is en
[INFO]	2023-01-11T16:22:10.745Z	cb0957dd-20de-4865-81da-1e267db14462	Locale is en
END RequestId: cb0957dd-20de-4865-81da-1e267db14462
REPORT RequestId: cb0957dd-20de-4865-81da-1e267db14462	Duration: 81.39 ms	Billed Duration: 82 ms	Memory Size: 512 MB	Max Memory Used: 50 MB

```

Thank you very much for the support

**Comment by DEADSEC-SECURITY** [comment]
What do you mean with Test tab? Did you try triggering the media_player with the skill id and checking if the echo dot speaks? Using developer test tab wont make it speak in your alexa.

**Comment by MrDrew514** [comment]
I'm sorry if I wasn't clear; I get the even triggered when I enter the 'actionable notification' (invocation name) in the Amazon Dev Test tab (Where we initially test the skill) doing this sends an event trigger in home assistant but when I run the script in home assistant with the right skill_id, the echodot does not speak.

**Comment by DEADSEC-SECURITY** [comment]
Are you logged in to you amazon account in HA? Can you share the code or print of what you did to trigger the skill via HA?

**Comment by MrDrew514** [comment]
Home Assistant is connected to my Amazon account with Nabu Casa and I'm using the token method which is working.

Script used

input_text:
![image](https://user-images.githubusercontent.com/82120740/212114772-f399b295-069d-45d0-89ce-f6f086285cbc.png)

script.yaml
![image](https://user-images.githubusercontent.com/82120740/212114506-cebf2620-166c-40c6-ab27-1bf8a2b13c90.png)

when I call the service
![image](https://user-images.githubusercontent.com/82120740/212115023-a2cdbc26-ac38-424e-8f17-90fd02d46a15.png)

there is nothing in the event
![image](https://user-images.githubusercontent.com/82120740/212117134-bf4a393d-e00a-4c49-81fb-0d7bfb93ac94.png)

When I enter 'actionable notifications' in the amazon dev 'test tab', Alexa respond with the text from the service called.
![image](https://user-images.githubusercontent.com/82120740/212117971-d6d57666-69a8-4d06-a9c2-06233c1e814c.png)

and the event is now showing 
![image](https://user-images.githubusercontent.com/82120740/212118263-2f0b4d27-b8b6-4c50-9f53-9a5a70622b23.png)

**Comment by MrDrew514** [comment]
I deleted all the logs in cloudwatch and I ran the script. It seems like no new logs are created.

I'm getting an error message accessing the cloudwatch logs which says

`User: arn:aws:sts::270144201668:assumed-role/VoiceHubSSORole/VoiceHubSSORole is not authorized to perform: cloudwatch:GetMetricData because no identity-based policy allows the cloudwatch:GetMetricData action`

AWS logs 

![image](https://user-images.githubusercontent.com/82120740/212154078-5222fc57-b33f-4f03-b5a9-6768cbfd7ec7.png)

**Comment by MrDrew514** [comment]
I think Nabu Casa is causing this.. It seems like it's not giving me the right permission to access the AWS services. Let me try the normal way and I'll get back to you asap.

**Comment by MrDrew514** [comment]
So I started from scratch with a different amazon account without Nabu Casa, and I'm still having the same issue where the script is not executing the audio, and no log is being generated in the cloudwatch logs.

Can it be because my Alexa is set to Canada/French and the skill is set to US/English ?

**Comment by MrDrew514** [comment]
UPDATE: I finally got it working using English/US with both skill and EchoDot. My echodot was set to French/CA or English/CA and it wasn't working. Once I changed my device language to US/English, it worked and I was able to hear it on the speak and the event was triggered.

Is it possible to make it work with the Echodot set to French/Canada ?
