### ISSUE TITLE
[Bug]: Utterance conflicts

### ISSUE THREAD

**Issue by MarcosMorelli** [keatontaylor/alexa-actions#161]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

marcos.eduardo.morelli@gmail.com

### What happened?

While creating the custom alexa skill, after importing the project the build fails due utterance conflicts.

### Version

master

### What Alexa device are you using?

Echo

**Comment by DEADSEC-SECURITY** [comment]
Can you please post the cloudwatch logs in the issue? @MarcosMorelli
