### ISSUE TITLE
Multiple Alexa Devices

### ISSUE THREAD

**Issue by moelloman** [keatontaylor/alexa-actions#166]
I'd like to use multiple Alexa devices in one automation, In my example I have 3 Alexa Dot devices on one floor . I'd like to respond to one notrification (send to all devices at the same time), doesn't matter in which room I am.  If from one of the players was fired the event then the action will be triggered. In case of parallel events (2 persons answer at the same time) then the first one wins.
I tried to use a media player group like
`target: media_player.groundfloor`
but it doesn't work/Isn't supported yet.
Instead of a group also a list of media players could be an option like 
`target: 
  - media_player.kitchen
  - media.player.livingroom` 
I don't know how complex the implementation would be. If feasible to do then I would be happy to have it in one of the next releases.
Many thanks in advance!

**Comment by elmar-hinz** [comment]
Basically this can only be done from within Home Assistant, by triggering the script multiple times once for each player.

The technical reason is, that a Skill is bound to the device calling the skill. Communication between multiple devices is limited to enterprise customers (health, hotels, etc.) by Amazon. That's how I understand it, but I didn't read the full docs of Amazon

There is a second issue. There is only one `input_text` to hold the spoken message. This makes a parallel usage more difficult. In this case the message is the same anyway.

**Comment by moelloman** [comment]
> Basically this can only be done from within Home Assistant by triggering the script multiple times once for each player. You would have to work this out for yourself. Then you can write the solution into the wiki.
> 
> The technical reason is, that a Skill is bound to the device calling the skill. (It's the alexa media player behind it, that triggers the skill for/from a device.) Communication between multiple devices is limited to enterprise customers (health, hotels, etc.) by Amazon. That's how I understand it, but I didn't read the full docs of Amazon. I am quite annoyed that Amazon doesn't openly tell the customers it is selling communication devices, that can only rudimentarily communicate.
> 
> There is a second issue. There is only one `input_text` to hold the spoken message. This makes a parallel usage more difficult. In this case the message is the same anyway.

Thanks @elmar-hinz for the detailed answer. I understand. Meanwhile I found an alternative by triggering the next device when ResponseNone was given on the previous etc. etc. This can be done endless.  
Therefore I close this request.

**Comment by chupacabra71** [comment]
>  Meanwhile I found an alternative by triggering the next device when ResponseNone was given on the previous etc. etc. This can be done endless. 

@moelloman sorry to revive an old thread, but could you share your code for this?
