### ISSUE TITLE
[Bug]: Getting error 503 on alexa skill, cant seem to access home assistant.

### ISSUE THREAD

**Issue by Ming-A** [keatontaylor/alexa-actions#167]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### What happened?

After following the guide, I have tried both long-lived access tokens and account linking, but I'm still getting error 503. My home assistant runs with Cloudflare tunnel and is accessible on the web.

![image](https://user-images.githubusercontent.com/41011175/213974763-949255f0-80d8-4e07-b999-330b319d5672.png)

### Version

v4.5.3 Alexa Media Player

### What Alexa device are you using?

Echo

**Comment by DEADSEC-SECURITY** [comment]
Also we have discord for these types of problem which we recommend since issues are reserved for actual bugs and not installation issues.

**Comment by Ming-A** [comment]
> This is probably not a bug but an issue with your installation. Are you using NABU CASA, Ducky DNS? Are you using SSL? Are you using tokens?
> 
> Dude I hate to be aggressive but I can't read minds, you need to share more info related to the problem. That picture doesnt tell me anything about your connection to HA

I am using Cloudflare tunnel with SSL from lets encrypt, and yes I have also placed my Long-Lived Access Tokens. Would join the discord group and ask again there.

![image](https://user-images.githubusercontent.com/41011175/214239103-5ef80beb-afdd-40f8-bd16-ae3319accc77.png)

**Comment by DEADSEC-SECURITY** [comment]
Token are known to be buggy. Can you try to use the login method?

**Comment by DEADSEC-SECURITY** [comment]
@Ming-A did you manage to fix it? Can I help you with it?

**Comment by Ming-A** [comment]
> @Ming-A did you manage to fix it? Can I help you with it?

Sorry for the late reply as I was away from home for a few days, As for the login method I'm not fully sure if i have done it right but this is how i have it setup,

![image](https://user-images.githubusercontent.com/41011175/215248465-0fd2c702-197c-4f2c-a0f5-4dcc52bfbffa.png)

**Comment by elmar-hinz** [comment]
For me the "login method" was the difficult solution. My old gateway does not support the loopback. 

Which top level domain are you using with Cloudflare? I did read once, they reject the free domains now.

To check the connection manually, I can recommend Postman. I did use it to explore the HA web API. The screenshot shows, it does also take a bearer token for to test it.

<img width="698" alt="Screenshot 2023-01-29 at 10 02 07" src="https://user-images.githubusercontent.com/1227339/215316148-c186e2cc-7239-4c41-9bf8-494bd09819ed.png">

**Comment by Ming-A** [comment]
> Which top level domain are you using with Cloudflare? I did read somewhere, they reject the free domains now.

Im got my domain from cloudflare directly when they offered domain services as well recently. TLD is .xyz, so something like https://homeassistant.mywebsite.xyz 

> To check the connection manually, I can recommend Postman. I did use it to explore the HA web API. The screenshot shows, it does also take a bearer token for to test it.

Have checked Postman and i have also gotten error 503, i think its to do with cloudflare security looking at the screenshot below
![image](https://user-images.githubusercontent.com/41011175/215335856-83d10c62-3acd-495e-93de-59f14d17222c.png)

**Comment by elmar-hinz** [comment]
The only recommendation I still can give is, check every log you can get hands on, Home Assistant, Postman, Cloudflare. Somewhere the actual reason of the issue should be mentioned. Also think of special logs of Add-ons for example NGINX.

**Comment by Ming-A** [comment]
> The only recommendation I still can give is, check every log you can get hands on, Home Assistant, Postman, Cloudflare. Somewhere the actual reason of the issue should be mentioned. Also think of special logs of Add-ons for example NGINX.

would take a look around and see what i can find, might even be a setting in Cloudflare directly but not sure

**Comment by DEADSEC-SECURITY** [comment]
Can you activate developer mode in cloudflare? @Ming-A it should remove any security check so you can check the theory of the anti-bot and if thats the case you can make it less sensitive or disable it in the firewall rules.

**Comment by Ming-A** [comment]
![image](https://user-images.githubusercontent.com/41011175/215505256-08c49b1b-cdbf-413a-9333-c7e2c44bcaa4.png)
Turning this off has fixed it as this is what prompts the JS challenge
