### ISSUE TITLE
Event not firing in HA

### ISSUE THREAD

**Issue by hawkseye76** [keatontaylor/alexa-actions#176]
I followed the wiki and got everything setup. The script asks the question, retrieves the answer, but the event is never fired in Home Assistant. There aren't any errors i can see. I enabled debug, and i don't see any errors in cloudwatch. I'm sure i'm probably missing something. Any help is greatly appreciated.
Here is one of the log files.

[log_file.txt](https://github.com/keatontaylor/alexa-actions/files/11174440/log_file.txt)

**Comment by hawkseye76** [comment]
A little more info.  My initial attempts were behind an nginx reverse proxy.  To see if it was maybe my setup, i flipped it over to a cloud account with a nabu casa url, and that doesn't work either.  I'm not getting any events fired from either url.

**Comment by JosXa** [comment]
I am also unable to get HA to send data to the skill. I triple-checked all steps from the wiki and am certain I have it set up correctly, but nothing shows up in Cloudwatch. I have configured the skill in the EU region in AWS, not sure if that matters...

**Comment by hawkseye76** [comment]
I can get HA to send data to the skill, but the skill doesn't send data back to reverse proxy url or nabu casa cloud url.  I can't manually fire events from api externally, so it's not being blocked.

**Comment by DEADSEC-SECURITY** [comment]
@JosXa did you use the correct skill id in the media_player? Is the media_player in HA the same account as the skill?

**Comment by hawkseye76** [comment]
Well, not sure what the deal was, but after a couple of reboots and recreating the amazon skill again, everything is working as expected now.
