### ISSUE TITLE
Language Localization

### ISSUE THREAD

**Issue by AngelofromTurin** [keatontaylor/alexa-actions#18]
Hi, Great component, Thanks a lot! 
I see that slowly we will have updates, would it be possible to add the localization of the language of Alexa's answers? 
The first time I replaced them autonomously for me in Italian but I understood that you will give us many upgrades and I would not want to get my hands on the code every time ...
Thanks so much :)

**Comment by keatontaylor** [comment]
Absolutely, I'd love to get localization integrated with this component. Right now beyond what you tell her to stay the only thing she current responds with is "Okay" when you say Yes/No or "You selected <something>" if the advanced features have been implemented.

There has been some awesome localization work on Alexa Media Player and I'd love to pull some of that over here if possible. Adding this as a future feature.

**Comment by AngelofromTurin** [comment]
Great! Thank You ! 
Now I expose you a problem: I have not tried the multiple choice yet, I am working only with yes or no, when I say "blabla" instead of yes or no Alexa replies "you triggered .. + (incomprehensible words -.- ')" and he stops doing nothing. I would like if he doesn't understand the command, repeat and try again so I tried to change the following lines and it works, I don't know if it is valid for all and it is useful but I submit it to you.
Thanks again for your great work :)
line 314
`        print("IntentReflectorHandler")
        intent_name = ask_utils.get_intent_name(handler_input)
        #speak_output = "You just triggered " + intent_name + "."
        speak_output = "Scusa, Non capisco. Rispondi solo si o no"
        return (
            handler_input.response_builder
                .speak(speak_output)
                .ask(speak_output) # Aggiunto da Angelo
                # .ask("add a reprompt if you want to keep the session open for the user to respond")
                .response
        )`

**Comment by Wizard99it** [comment]
I built isodate==0.6.0 but with the newest version 0.7.2 features all speak-out in italian - tested on Hassio 0.109.5 - Alexa Player v2.8.0 and all works fine. With your permission i'll upolad the files.

**Comment by AngelofromTurin** [comment]
Wow ! Off Course ! If i can help you with translation i’ll love do it :)

**Comment by keatontaylor** [comment]
@Wizard99it please upload what you cannot would be super helpful

**Comment by Wizard99it** [comment]
Honored to be useful, I used alexa actions with ResponseYes and it works great. All in Italian. I am happy to be able to help translate for later versions.
[lambda_ITA.zip](https://github.com/keatontaylor/alexa-actions/files/4805023/lambda_ITA.zip)
