### ISSUE TITLE
ResponseNumeric understood as date

### ISSUE THREAD

**Issue by PaulBiod** [keatontaylor/alexa-actions#186]
Hi,

I am trying to use the responseNumeric, but alexa always understand my numbers as dates, no matter if I say "One", "Two", etc.
I'm joining a printscreen of the evaluate module on alexa's developper page, as you can see, if I say "three" (in french) it's understood as a date.
![Capture d’écran 2023-05-25 134315](https://github.com/keatontaylor/alexa-actions/assets/28720176/2738af70-5d56-4251-9f81-5d96a0c361b7)

**Comment by DEADSEC-SECURITY** [comment]
Does this happen in english too?

**Comment by PaulBiod** [comment]
Hi,
yes, I also tried english.
But I realised when building the skill, that I had an error (related to the string intent (because of the space, I applied the fix with AMAZON.Person). After fixing this error and building again the skill, it finally works as expected.

**Comment by DEADSEC-SECURITY** [comment]
If this was a issue with the code in the repo @PaulBiod please point it out or start a PR to fix the issue.

**Comment by PaulBiod** [comment]
Hi,
it's an already know bug related to the intents (strings).
I followed the instructions to fix it, and now, I can build the skill again, and everything is working.
Thanks
