### ISSUE TITLE
[Bug]: Randomly won't listen for answers

### ISSUE THREAD

**Issue by PaulBiod** [keatontaylor/alexa-actions#187]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

scriptsgratuits@gmail.com

### What happened?

Randomly, when I use the actionable notification for more than one question (exemple : do you want to switch on the fan ? -> yes -> which fan speed do you want ? -> One)

At the second question, or the third, even when I add delays between questions, the echo show won't listen to my answer, I mean, the blue line on the bottom of the echo that shows you alexa is listening won't appear.

### Version

the last

### What Alexa device are you using?

Echo Show

### Relevant log output

```shell
I have nothing related to the issue on the HA logs
```

**Comment by PaulBiod** [comment]
I realised I am using the 0.8.2 version.
How is the update process ? I have to replace  the lambda files in the amazon dev console ?
thanks

**Comment by DEADSEC-SECURITY** [comment]
I would suggest recreating the skill @PaulBiod with version 0.9 or the master branch.

master branch has untested features so proceed but expect bugs or issues.

**Comment by PaulBiod** [comment]
Hi,
I installed the skin on April, 20th
So I guess it was the last version, right ?
If not, I didn't see any differences on the lambda_function.py since 0.8.2.
You said to recreate the skill, but if I recreate it, it will be the same files (except locals but it doesn't make any difference I guess, I am using fr_FR)

![Capture](https://github.com/keatontaylor/alexa-actions/assets/28720176/6555dc5b-f264-481a-b9e2-3964a572ce96)

**Comment by DEADSEC-SECURITY** [comment]
The fresh install will do much more then update the code, it will clear caches, configurations etc which is intended cuz if it works the second time it couldve been because you miss configured something from the start.

**Comment by PaulBiod** [comment]
I forgot to mention that I have automations that work perfectly (with 10 seconds between the questions), and next day, they won't. It's really random, but one of them (2 questions, the one you see in the video) never worked for the second question. If it was a problem of configuration, it would never work I suppose.
Have to mention also, that I had to change the file with the intents cause strings and numbers were not working correctly (fr_FR) and now they work, that 's why I m not very pleased with the idea of install from scratch.
With a google search, I saw that some people had the same problem, and solved it with a delay between question, that s what I did, but it randomly fail 
I m not sure what to do..

**Comment by DEADSEC-SECURITY** [comment]
Dude can you just do what I asked and give me feedback?

**Comment by PaulBiod** [comment]
So, I found the problem.
Let me explain : 

Test 1 : 
first question = > response Yes => delay 10 seconds => question 2 : it works

Test 2 : 
first question= > response Yes => send a notification via alexa show => delay 10 seconds => question 2 : it fails

test 3 : 
first question= > response Yes => delay 10 seconds => send a notification via alexa show => delay 10 seconds => question 2 : it works
