### ISSUE TITLE
ResponseNumeric 

### ISSUE THREAD

**Issue by Toolmaster30** [keatontaylor/alexa-actions#196]
Hello, first of all a big thank you for this code. But would it also be possible for Alexa to accept the numbers in German with ResponseNumeric?

Greetings George

**Comment by DEADSEC-SECURITY** [comment]
Related to: https://github.com/keatontaylor/alexa-actions/pull/189

Currently only supports 4 digit numbers

**Comment by DEADSEC-SECURITY** [comment]
Feel free to test that PR modifications and giving some feedback so we can make it a part of the code soon.

**Comment by Toolmaster30** [comment]
Thanks now it works perfectly.
