### ISSUE TITLE
Possible typo at lambda_function.py?

### ISSUE THREAD

**Issue by somar05** [keatontaylor/alexa-actions#2]
Maybe the line #93 has a typo:

'{}/api/events/alexa_actionable_**notificaiton**'.format(HOME_ASSISTANT_URL),

Should be like this?
'{}/api/events/alexa_actionable_**notification**'.format(HOME_ASSISTANT_URL),

Maybe it has an impact when calling the service

**Comment by keatontaylor** [comment]
Ah yes should be, I’ve updated the lambda code
