### ISSUE TITLE
[Bug]:  Skill-Test schlägt fehl

### ISSUE THREAD

**Issue by Romero-KCBS2003** [keatontaylor/alexa-actions#203]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

matthias.michel1986@outlook.de

### What happened?

Bei der Installation auf der Amazon-Developer-Seite kommt bei mir als Antwort immer: "Timer werden derzeit auf diesem Gerät nicht unterstützt". Ich habe das Setup laut Anleitung mehrfach geprüft und kann keinen Fehler entdecken 😑

![image](https://github.com/keatontaylor/alexa-actions/assets/135272332/a7781036-fce4-4e16-aa7f-65a66f1f21c5)

![image](https://github.com/keatontaylor/alexa-actions/assets/135272332/3f0b6e49-e54e-46a5-a36d-c4f4c52afef5)

![image](https://github.com/keatontaylor/alexa-actions/assets/135272332/491a4c50-f7ca-4d2e-a176-69031d0257f3)

![image](https://github.com/keatontaylor/alexa-actions/assets/135272332/a840f70f-e8ea-4fb7-847e-eed59748ea0d)

![image](https://github.com/keatontaylor/alexa-actions/assets/135272332/020620ef-d7ba-4dc6-a591-cbc5ac52d0f9)
*das unknown am Textbeginn wurde entfernt -> keine Änderung

Habe ich etwas übersehen?

Danke und viele Grüße

### Version

2023.8.4

### What Alexa device are you using?

Other

**Comment by DEADSEC-SECURITY** [comment]
Hi, I know that this was developer by a german guy, but I don't speak german and also keep it in english so future users can read this too.

**Comment by DEADSEC-SECURITY** [comment]
You probably have an older Alexa device so you will need to disable the Timers intent by removing it from the intents file.

I suppose your using german so in your `skill-package/interactionModels/custom/de-DE.json` file you need to remove:
```
{
          "name": "Duration",
          "slots": [
            {
              "name": "Durations",
              "type": "AMAZON.DURATION"
            }
          ],
          "samples": [
            "{Durations}"
          ]
        },
        {
          "name": "Date",
          "slots": [
            {
              "name": "Dates",
              "type": "AMAZON.DATE"
            },
            {
              "name": "Times",
              "type": "AMAZON.TIME"
            }
          ],
          "samples": [
            "{Dates} um {Times}",
            "um {Times}",
            "{Dates}"
          ]
        }
```

Let me know if that worked.

**Comment by Romero-KCBS2003** [comment]
I have delete it but the answer from Alexa is the same like before: "Timer werden derzeit auf diesem Gerät nicht unterstützt"("Timers are not currently supported on this device") 😑
