### ISSUE TITLE
[Bug]:  There was a problem with the Skill request response

### ISSUE THREAD

**Issue by lotablet** [keatontaylor/alexa-actions#212]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

lore.tavola@gmail.com

### What happened?

Hello, i just re-installed again this amazing feature because i was wrong and I deleted all skill.

But now i'm stuck with this message when i test the skill:

"There was a problem with the Skill request response" 

i've follow exactly the guide (because i've do it before and worked like a charm)

### Version

v0.10.1

### What other Alexa device are you using?

Echo Show, Echo Dot

### Relevant log output

```shell
# output of alexa when i say "open actionable notifications"

none

**Comment by lotablet** [comment]
changed title because  now it say this, i've do nothing O_O

**Comment by lotablet** [comment]
changed title because i tried to change Endpoint to my HASSOS server, and now it say this.

I noticed there was some errors related to Endpoint. 

Then tried to switch Endpoint to AWS Lambda ARN with default values and it say again: 

"Welcome, you can say Hello or Help. Which would you like to try?"

so this is the problem but i don't know what i can do to get this working

please help me

**Comment by DEADSEC-SECURITY** [comment]
Need logs, also release latest means nothing, is it master? v0.10.1? Be more specific please

**Comment by lotablet** [comment]
> Need logs, also release latest means nothing, is it master? v0.10.1? Be more specific please

Yes it's 0.10.1 because i tried yesterday without success.

Sorry i'm only a user, where can i get logs? You mean logs from alexa developer console?

**Comment by DEADSEC-SECURITY** [comment]
Yes developer console in alexa you have cloudwatch. And also if you could get me logs from home assistant that would help too.

**Comment by lotablet** [comment]
i cleared all my registy and i tried to fire "open actionable notifications" in test mode and from script in my home assistant.

there is only this warning message: 

Logger: homeassistant.helpers.template
Source: helpers/template.py:2209
First occurred: 17:40:16 (1 occurrences)
Last logged: 17:40:16

Template variable warning: 'suppress_confirmation' is undefined when rendering '{"text": "{{ text }}", "event": "{{ event_id }}", "suppress_confirmation": "{{ suppress_confirmation }}"}'


and this is my log in A.D.C (attached below)


[log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/13063812/log-events-viewer-result.csv)

**Comment by DEADSEC-SECURITY** [comment]
Your using master branch not version v0.10.1. Please update your code with the latest master branch code which has been fixed for the bug your getting or install version v0.10.1 which is the latest stable one.

**Comment by DEADSEC-SECURITY** [comment]
Also make sure to pass all necessary parameters like the home assistant warning states. You need to `suppress_confirmation` when calling the script

**Comment by lotablet** [comment]
> Your using master branch not version v0.10.1. Please update your code with the latest master branch code which has been fixed for the bug your getting or install version v0.10.1 which is the latest stable one.

Sorry i've follow guide and i used template from .https://github.com/keatontaylor/alexa-actions.git as guide says

**Comment by DEADSEC-SECURITY** [comment]
> > Your using master branch not version v0.10.1. Please update your code with the latest master branch code which has been fixed for the bug your getting or install version v0.10.1 which is the latest stable one.
> 
> Sorry i've follow guide and i used template from .https://github.com/keatontaylor/alexa-actions.git as guide says
> 

The guide is outdated add a new param for the notification supression and set it as false

**Comment by lotablet** [comment]
Ok nice thanks for help ❤️

Il dom 22 ott 2023, 19:28 Antonio ***@***.***> ha scritto:
