### ISSUE TITLE
Connect AlexaSkill to Homeassistant with synology.me Adress

### ISSUE THREAD

**Issue by lindma2** [keatontaylor/alexa-actions#217]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

magnus.untiedt@gmail.com

### What happened?

Hello everybody,

Unfortunately, I don't know what to do. I've followed the instructions and just can't get a connection between my Home Assistant and my Alexa skill. I suspect that it is due to the URL but unfortunately I am not sure.

I have a synology.me address.
This is redirected in Synology NAS via reverse proxy from port 443 to the internal IP:8123. Via NabuCasa etc. everything also works as desired.

Has anyone here ever successfully managed this and linked the Alexa skill to a synology.me address?

I have tried to access Homeassistant via the token

Thanks a lot

Best Regards Magnus

### Version

2.1.1

### What Alexa device are you using?

Echo

**Comment by DEADSEC-SECURITY** [comment]
Are you using a proper SSL cert?
