### ISSUE TITLE
Fourth response state:  ResponseStop?

### ISSUE THREAD

**Issue by Sp4rky001** [keatontaylor/alexa-actions#218]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a nice to have.  Currently, there are three possible response states:  ResponseYes, ResponseNo, and ResponseNone.  In the case of a garage, I'd like to be able to do this:
-  Alexa:  The garage is still open, would you like me to close it?
-  Me: No/No response
- Alexa: Ok, I will ask again in 10 minutes.

-  Alexa:  The garage is still open, would you like me to close it?
-  Me: Stop asking
- Alexa: Ok, I will not ask again.

**Describe the solution you'd like**
In a normal case, I would like Alexa to remind me that the garage is still open every 10 minutes, but if I intend on leaving the door open for a few hours, I would like to be able to ask Alexa to turn off the reminder (disable the trigger node in node-red) by a voice prompt.  A fourth response state of ResponseStop would help to do this.

**Describe alternatives you've considered**
The alternative solution is to open node red and redeploy the flow to reset all nodes.

**Additional context**
none

**Comment by DEADSEC-SECURITY** [comment]
There is a event for strings (StringIntentHandler) but for it to work you have to add the strings to the language you're using.
under `skill-packages/interactionModels/custom` you can change the `json `file of your language.

Under strings:
```
{
          "name": "String",
          "slots": [
            {
              "name": "Strings",
              "type": "AMAZON.Person"
            }
          ],
          "samples": [
            "{Strings}"
          ]
        },
```
you can add your samples and hopefully it should work.

**Comment by DEADSEC-SECURITY** [comment]
You can also do this via the console:
![image](https://github.com/keatontaylor/alexa-actions/assets/45077772/dbc18225-5aed-4a90-99a4-c19f0c6e675b)

**Comment by Sp4rky001** [comment]
Thank you for your suggestion.  I will try this.  It took me a while to revisit this issue until now.  Thanks!
