### ISSUE TITLE
Custom Action - Cannot Communicate With Home Assistant

### ISSUE THREAD

**Issue by Tx-ST-Home** [keatontaylor/alexa-actions#22]
I certainly appreciate all your efforts to contribute a terrific new custom skill for Alexa and Home Assistant. I somewhat new to HA so the issues I maybe having are just me getting up on the learning curve. I'm running HASSIO (V0.109.6) on a RPI3+ with the latest Alexa Media Player integration (V2.7.3). 

I followed the instructions on creating and deploying the "custom action" skill and successfully linked in my Alexa app. 

![Alexa Actions Account Linking](https://user-images.githubusercontent.com/22216920/81744198-83fb1000-9468-11ea-8052-cb196f876777.JPG)

When I attempt to verify the new custom action with the command "Alexa, open custom actions" the response is "Could not communicate with Home Assistant". 

Any advice or direction would certainly be much appreciated and thanks again for your efforts. 

Cheers,

**Comment by schoenof** [comment]
I had the same problem...for me it was because I had a / at the end of my home assistant URL in the Alexa skill code....later in the code it already adds a / so it was double //....might not be your issue but I know it is an easy mistake to make....

**Comment by Tx-ST-Home** [comment]
> I had the same problem...for me it was because I had a / at the end of my home assistant URL in the Alexa skill code....later in the code it already adds a / so it was double //....might not be your issue but I know it is an easy mistake to make....

I certainly appreciate your response. I've verified my HA URL is properly formatted as

HOME_ASSISTANT_URL = 'https://MY_HA.duckdns.org'

To aid in tracking down the source of the issue I modified the lambda_function.py code to by adding an error number prefix to the Alexa response "Could not communicate with home assistant" if  response.status >= 400 codes.  With that in place it appears my error is associated with an error in the def get _ha_state(self): code segment. I'm not familiar with python code and at a disadvantage on steps to trouble shoot this issue but certainly will keep trying.

**Comment by keatontaylor** [comment]
@Tx-ST-Home highly suggest you join the [Discord](https://discord.gg/3Ubwur) channel (#Alexa-actionable-notificaitons) will make it easier to help with realtime debugging.

**Comment by honkerst** [comment]
I had this error when the HA API wasn't accessible. Try `curl -X GET -H "Authorization: Bearer LONG_LIVED_TOKEN" -H "Content-Type: application/json" https://YOUR_HA_URL/api/config` it probably returns an error. Mine was a 503 forbidden, I hadn't turned the HA api on.

**Comment by keatontaylor** [comment]
Please try the latest code in this repo for the lambda_function.py.

**Comment by Tx-ST-Home** [comment]
@Keatontaylor, 
Thank you for the enhanced error code parsing in your latest release of lambda_function.py (V0.5.2).

When I activate the "Open Custom Actions" with the latest release (V0.5.2) with "Open Custom Actions"  it fails in the "def post_ha_event" code segment with  the response.status of 404 error "It looks I may not be able to find the input text entity. Please check that you've added it to home assistant and try again" 

I recognize my limitations in this domain and will follow your suggestion to engage the Discord community. Now all I need to do is get started with Discord which is also new to me ... but hey if I didn't want the challenge I'd just stick to the commercial off the shelve solutions and where's the challenge with that. 

Thanks again for you efforts and somewhere down the line I hope to be able to provide support for other noobs. 

Cheers,

**Comment by Tx-ST-Home** [comment]
> I had this error when the HA API wasn't accessible. Try `curl -X GET -H "Authorization: Bearer LONG_LIVED_TOKEN" -H "Content-Type: application/json" https://YOUR_HA_URL/api/config` it probably returns an error. Mine was a 403 forbidden, I hadn't turned the HA api on.

@honkerst  I took your suggestion and executed the cURL command you were kind enough to provide. My results were different than yours. Here are the results of mine: 

curl -X GET -H "Authorization: Bearer LONG_LIVED_TOKEN" -H "Content-Type: application/json" https://my_ha.duckdns.org/api/config
401: Unauthorized

**Comment by Tx-ST-Home** [comment]
Found the issue was the typical noop problem. Thanks for the help.
