### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by F250SC** [keatontaylor/alexa-actions#223]
### What happened?

So far the installation/configuration went totally fine.
Until the Hello World test.

I did the exact ways how it is described and this is what happened.

First few times the Echo Dot was asking "Yes or no" but the response text didn't show up at the dashboard in the text field.
And then she just answered with the "Error 404" thing. I tried to go back all the steps, but always there is a problem.

I use the NabuCasa connection.

Any suggestions?
Or what do I miss here? 

### Version

newest (Home Assistant and Alexa-Actions)

### What Alexa device are you using?

Echo

### What other Alexa device are you using?

none

**Comment by DEADSEC-SECURITY** [comment]
The skill doesnt update the text field. It triggers an event on response

**Comment by F250SC** [comment]
as I understand, it should do that according to my response...?

![image](https://github.com/keatontaylor/alexa-actions/assets/70237345/c179f3eb-fa4c-40ee-9c69-32a0bb429278)

**Comment by DEADSEC-SECURITY** [comment]
I need to see you config. You miss configured something. Also listen for the event in the developer tools and trigger it send me what it displays.
