### ISSUE TITLE
Error coming If English India is selected as Locale

### ISSUE THREAD

**Issue by vineeshvijayan2020** [keatontaylor/alexa-actions#230]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### What happened?

Error coming If English India is selected as Locale and when import skills is selected this error message comes

![image](https://github.com/keatontaylor/alexa-actions/assets/72342750/57aee69a-4145-4ac5-9a2a-d3b3ecf4450f)
What I can do to rectify this?

### Version

Latest

### What Alexa device are you using?

Echo

**Comment by vineeshvijayan2020** [comment]
I am able to add it now by selecting English US. But now the response of Yes or No is not registered. Only ResponseNone is coming when event is set to start listening

**Comment by ashoktvm** [comment]
Same issue happens to me. When I select India it doesn't import the skill. This is the response it get

![image](https://github.com/keatontaylor/alexa-actions/assets/45116583/ae553cc3-85fe-4db8-b573-4dcc54b4b22b)

**Comment by ohuc** [comment]
There is a simple workaround set the lanaguage to english(US)/hindi and change the voice to Indian in the Alexa app

**Comment by DEADSEC-SECURITY** [comment]
We currently don't support Hindi in the skill, if you would like to contribute and add such language we would appreciate.

**Comment by ohuc** [comment]
well i'd love to contribute to add hindi

**Comment by DEADSEC-SECURITY** [comment]
Feel free to do so and open a PR

**Comment by DEADSEC-SECURITY** [comment]
Fixed on latests release
