### ISSUE TITLE
Is there any way to get a responseString? 

### ISSUE THREAD

**Issue by ohuc** [keatontaylor/alexa-actions#231]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Want a response type where you can get the entire transcript of what was said on the alexa device.

**Describe alternatives you've considered**
No other alternatives.

**Additional context**
This is not related to the ResponseSelection, where the response is a predefined selection

**Comment by DEADSEC-SECURITY** [comment]
You need to modify the interactionModels yourself and add the string your want to capture to the Strings object
