### ISSUE TITLE
There was an issue creating your skill. Skill resources were not provisioned. Please try again later. 

### ISSUE THREAD

**Issue by Krispkiwi** [keatontaylor/alexa-actions#234]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### What happened?

This error appears when importing the github repo

### Version

Fresh Import

**Comment by gioefede90** [comment]
i confirm same issue - i've tried with different PCs and different browsers but problem still occur.
additional info: if you continue (after the error) the system create two skills with the same name, the first have many incorrect parts (example code is different compared to the one on github), the second skill is totally incomplete (for example endpoint is missing).

**Comment by gioefede90** [comment]
> > i confirm same issue - i've tried with different PCs and different browsers but problem still occur. additional info: if you continue (after the error) the system create two skills with the same name, the first have many incorrect parts (example code is different compared to the one on github), the second skill is totally incomplete (for example endpoint is missing).
> 
> Have you found a solution?

nope, i've tried to manually import/copy the code from github to the skill but i get stuck during test phase, i'm surely missing something or maybe import procedure put some data that i cannot put manually. hope they fix this soon, i cannot use this tool as of today.

**Comment by Varguit** [comment]
Same problem here.
Also tried to copy all files inside lambda folder without success :(

I'm gonna try other methods. I will report back as soon as I find a method that works...

**Comment by Krispkiwi** [comment]
> Same problem here. Also tried to copy all files inside lambda folder without success :( I've checked my external URL is ok
> 
> I'm gonna try other methods. I will report back as soon as I find a method that works...
> 
> Edit: After trying with an account linking, still not working... Testing always results in: An error has occurred with the response from the Skill you requested (translated from spanish)

I tried to report it to amazon, they came back with "Choose a different region" despite it happening to people all over the planet...

**Comment by thegabriele97** [comment]
Hi, I'm having the same issue. Tried all the available regions but no luck

**Comment by Lewis-house** [comment]
I've been trying for 2 days but same problem

**Comment by Krispkiwi** [comment]
Is it deadsec maintaining this now or is Keaton still involved?

**Comment by Krispkiwi** [comment]
Tried again this morning, error is still occurring

**Comment by DEADSEC-SECURITY** [comment]
You guys need to manually import the skill. The automated skill import is currently now working.

**Comment by DEADSEC-SECURITY** [comment]
Well my initial fix did not work. Apparently all libraries install and exist in python 3.11. So for now I dont have a solution. Ill keep you guys posted

**Comment by Krispkiwi** [comment]
> You guys need to manually import the skill. The automated skill import is currently now working.

I've tried manually importing the code, that didn't work. Is there anything additional we need to import and if so how?

**Comment by BoGnY** [comment]
same problem.. tried all language and all region 😢
