### ISSUE TITLE
[Bug]: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by nu00** [keatontaylor/alexa-actions#238]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### What happened?

Just updated to version 0.12.1 and in logs I get:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'typing_extensions'
Traceback (most recent call last):
```

I've also tried adding typing_extensions in requirements.txt but no success.
I've tried the Binary version but it dosen't let me upload binary files.

### Version

0.12.1

### What Alexa device are you using?

Echo, Other

### What other Alexa device are you using?

Echo Flex

### Relevant log output

```shell
INIT_START Runtime Version: python:3.8.v43	Runtime Version ARN: arn:aws:lambda:eu-west-1::runtime:b20481443932830049531ab20faaf09295061aff7a67a0b0f40496e5e1ddec59
START RequestId: 5480ade9-32a6-4852-bc3a-e06d6b807246 Version: 12
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'typing_extensions'
Traceback (most recent call last):
END RequestId: 5480ade9-32a6-4852-bc3a-e06d6b807246
REPORT RequestId: 5480ade9-32a6-4852-bc3a-e06d6b807246	Duration: 3.94 ms	Billed Duration: 4 ms	Memory Size: 512 MB	Max Memory Used: 49 MB	Init Duration: 300.18 ms
```

**Comment by snakuzzo** [comment]
Importing [this file](https://raw.githubusercontent.com/python/typing_extensions/main/src/typing_extensions.py) under lambda directory skill works fine.

**Comment by Scialla** [comment]
after importing `typing_extensions.py` under lambda directory, skill work but, after response to any alexa question, variable `notification_response` and `notification_response_type` are not valued whatever the answer, except for `ResponseNone`

Alexa vocal response is someone like "you just trigger the low word intent" or similar, i don't understand exactly "the low word"

**Comment by pesi75** [comment]
> after importing `typing_extensions.py` under lambda directory, skill work but, after response to any alexa question, variable `notification_response` and `notification_response_type` are not valued whatever the answer, except for `ResponseNone`
> 
> Alexa vocal response is someone like "you just trigger the low word intent" or similar, i don't understand exactly "the low word"

I think the response is: "You just triggered AMAZON.FallbackIntent."

**Comment by pesi75** [comment]
Yes and the log in the developer console report "Reflector Intent triggered" 

> after importing `typing_extensions.py` under lambda directory, skill work but, after response to any alexa question, variable `notification_response` and `notification_response_type` are not valued whatever the answer, except for `ResponseNone`
> 
> Alexa vocal response is someone like "you just trigger the low word intent" or similar, i don't understand exactly "the low word"

Yes and the log in the developer console report "Reflector Intent triggered"

**Comment by Scialla** [comment]
> > after importing `typing_extensions.py` under lambda directory, skill work but, after response to any alexa question, variable `notification_response` and `notification_response_type` are not valued whatever the answer, except for `ResponseNone`
> > Alexa vocal response is someone like "you just trigger the low word intent" or similar, i don't understand exactly "the low word"
> 
> Yes and the log in the developer console report "Reflector Intent triggered"

yes, i read log and saw what it said ( Reflector Intent triggered) but i don't think vocal response is "AMAZON.Fallback"

**Comment by marsal-75** [comment]
> > > after importing `typing_extensions.py` under lambda directory, skill work but, after response to any alexa question, variable `notification_response` and `notification_response_type` are not valued whatever the answer, except for `ResponseNone`
> > > Alexa vocal response is someone like "you just trigger the low word intent" or similar, i don't understand exactly "the low word"
> > 
> > 
> > Yes and the log in the developer console report "Reflector Intent triggered"
> 
> yes, i read log and saw what it said ( Reflector Intent triggered) but i don't think vocal response is "AMAZON.Fallback"

You are right, my mistake.

**Comment by DEADSEC-SECURITY** [comment]
Well this bug did not happen to me when I made the install of V0.12.1 but I can add this library to the requirements. I'm running the same runtime python3.8V42 so I'll add this to the build process and launch version 0.12.2

**Comment by DEADSEC-SECURITY** [comment]
v0.12.2 is out to address this issue
