### ISSUE TITLE
Doesn't seem to be asking the question

### ISSUE THREAD

**Issue by jokesters** [keatontaylor/alexa-actions#24]
When I trigger the automation i get "Sorry, I'm having trouble getting what you asked. Please try again" message.  it says it twice.  I came to realize its waiting on a response so i try saying yes or no and it says ok..  still not getting the automation from the response to trigger yet either, but i need to figure out where I'm going wrong on having it say the message to know its looking for an answer first.

**Comment by keatontaylor** [comment]
Hey @jokesters, please join the #alexa-actionable-notifications discord channel [Here](https://discord.gg/AWgE6g). Makes it super easy for us to help you in real time :)
