### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vulcanjedi** [keatontaylor/alexa-actions#243]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

vncraigslist+aan@hotmail.com

### What happened?

LONG time HA user, first time Alexa Actionable Notifications/Media Player user.
Went thru the github.
Invocation updated, build/deployed model and code
Using LL token, DDNS, nginx proxy manager.
Docker full img install on  ubuntu
The Alexa Test simulator worked, prompted yes/no but then responds You just triggered AMAZON.FallbackIntent.
When proceeding to the Hello World Exercise, yes /no again is prompted but listening on the event bus yields nothing.
From the automations tab it shows the HW Response automation has never been triggered?

### Version

0.12.2

### What Alexa device are you using?

Echo

### What other Alexa device are you using?

Yamaha Soundbar w/ Alexa native integration

### Relevant log output

```shell
I'm unclear of which logs and where to procure these. I set DEBUG to true in the Alexa Dev console
```

**Comment by DEADSEC-SECURITY** [comment]
Cloudwatch logs via the alexa console code editorSent from my Galaxy
-------- Original message --------From: vulcanjedi ***@***.***> Date: 3/8/24  2:15 PM  (GMT-08:00) To: keatontaylor/alexa-actions ***@***.***> Cc: Antonio ***@***.***>, Assign ***@***.***> Subject: [keatontaylor/alexa-actions] [Bug]:  (Issue #243) 
Did you check our FAQ and Issue/PR for similar issues?

 FAQ checked!
 Issues/PR checked!

Contact Details
***@***.***
What happened?
LONG time HA user, first time Alexa Actionable Notifications/Media Player user.
Went thru the github.
Invocation updated, build/deployed model and code
Using LL token, DDNS, nginx proxy manager.
Docker full img install on  ubuntu
The Alexa Test simulator worked, prompted yes/no but then responds You just triggered AMAZON.FallbackIntent.
When proceeding to the Hello World Exercise, yes /no again is prompted but listening on the event bus yields nothing.
From the automations tab it shows the HW Response automation has never been triggered?
Version
0.12.2
What Alexa device are you using?
Echo
What other Alexa device are you using?
Yamaha Soundbar w/ Alexa native integration
Relevant log output
I'm unclear of which logs and where to procure these. I set DEBUG to true in the Alexa Dev console

**Comment by vulcanjedi** [comment]
```
#timestamp,message
1709940515099,"INIT_START Runtime Version: python:3.8.v43	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:b20481443932830049531ab20faaf09295061aff7a67a0b0f40496e5e1ddec59
"
1709940515547,"START RequestId: 272018d2-1956-4fe7-b088-59c91a065e29 Version: 6
"
1709940515589,"Locale is en
"
1709940515589,"[INFO]	2024-03-08T23:28:35.589Z	272018d2-1956-4fe7-b088-59c91a065e29	Locale is en
"
1709940515874,"Raw response: b'{""entity_id"":""input_text.alexa_actionable_notification"",""state"":""{\\""text\\"": \\""Yes or no?\\"", \\""event\\"": \\""hello_world\\"", \\""suppress_confirmation\\"": \\""\\""}"",""attributes"":{""editable"":true,""min"":0,""max"":255,""pattern"":null,""mode"":""text"",""icon"":""mdi:account-voice"",""friendly_name"":""alexa_actionable_notification""},""last_changed"":""2024-03-08T20:51:10.695193+00:00"",""last_updated"":""2024-03-08T20:51:10.695193+00:00"",""context"":{""id"":""01HRFXB177RSGA3TN666RR4BWJ"",""parent_id"":null,""user_id"":null}}'
"
1709940515874,"[DEBUG]	2024-03-08T23:28:35.874Z	272018d2-1956-4fe7-b088-59c91a065e29	Raw response: b'{""entity_id"":""input_text.alexa_actionable_notification"",""state"":""{\\""text\\"": \\""Yes or no?\\"", \\""event\\"": \\""hello_world\\"", \\""suppress_confirmation\\"": \\""\\""}"",""attributes"":{""editable"":true,""min"":0,""max"":255,""pattern"":null,""mode"":""text"",""icon"":""mdi:account-voice"",""friendly_name"":""alexa_actionable_notification""},""last_changed"":""2024-03-08T20:51:10.695193+00:00"",""last_updated"":""2024-03-08T20:51:10.695193+00:00"",""context"":{""id"":""01HRFXB177RSGA3TN666RR4BWJ"",""parent_id"":null,""user_id"":null}}'
"
1709940515874,"Decoded response: {""text"": ""Yes or no?"", ""event"": ""hello_world"", ""suppress_confirmation"": """"}
"
1709940515874,"[DEBUG]	2024-03-08T23:28:35.874Z	272018d2-1956-4fe7-b088-59c91a065e29	Decoded response: {""text"": ""Yes or no?"", ""event"": ""hello_world"", ""suppress_confirmation"": """"}
"
1709940515874,"event_id='hello_world' suppress_confirmation=False text='Yes or no?'
"
1709940515874,"[DEBUG]	2024-03-08T23:28:35.874Z	272018d2-1956-4fe7-b088-59c91a065e29	event_id='hello_world' suppress_confirmation=False text='Yes or no?'
"
1709940515876,"END RequestId: 272018d2-1956-4fe7-b088-59c91a065e29
"
1709940515876,"REPORT RequestId: 272018d2-1956-4fe7-b088-59c91a065e29	Duration: 328.88 ms	Billed Duration: 329 ms	Memory Size: 512 MB	Max Memory Used: 57 MB	Init Duration: 447.87 ms	
"
1709940520641,"START RequestId: 960b919e-3097-4bd0-9fd9-2b7819c37040 Version: 6
"
1709940520643,"Locale is en
"
1709940520643,"[INFO]	2024-03-08T23:28:40.643Z	960b919e-3097-4bd0-9fd9-2b7819c37040	Locale is en
"
1709940520643,"[INFO]	2024-03-08T23:28:40.643Z	960b919e-3097-4bd0-9fd9-2b7819c37040	Reflector Intent triggered
"
1709940520643,"Reflector Intent triggered
"
1709940520644,"END RequestId: 960b919e-3097-4bd0-9fd9-2b7819c37040
"
1709940520644,"REPORT RequestId: 960b919e-3097-4bd0-9fd9-2b7819c37040	Duration: 4.38 ms	Billed Duration: 5 ms	Memory Size: 512 MB	Max Memory Used: 58 MB	
"
```

**Comment by vulcanjedi** [comment]
The Yes/No Intents were missing.
