### ISSUE TITLE
Speaking to alexa

### ISSUE THREAD

**Issue by shedman214** [keatontaylor/alexa-actions#253]
Making an automation with the alexa_actionable_notification. I have multiple alexa devices, is there a way for HA to know which alexa device i speak to. So I can have that alexa device specially respond to me instead of assigning a specific alexa device?

**Comment by DEADSEC-SECURITY** [comment]
Not currently but possibly by editing the payload

**Comment by shedman214** [comment]
> Not currently but possibly by editing the payload

How owuld i accomplish that?

**Comment by DEADSEC-SECURITY** [comment]
I might make a new version to support this. But it involves changing the code
