### ISSUE TITLE
Show indentation error in code as Alexa says "There was a problem that the requested skill response"

### ISSUE THREAD

**Issue by yjp909** [keatontaylor/alexa-actions#27]
Following  code "indentation error" on lambda_function.py on Amazone Dev. console

129        return "Okay"
        
131    def get_value_for_slot(self, handler_input, slot_name):
132        """"Get value from slot, also know as the (why does amazon make you do this code)"""
133        slot = ask_utils.get_slot(handler_input, slot_name=slot_name)
134        if slot and slot.resolutions and slot.resolutions.resolutions_per_authority:
135            for resolution in slot.resolutions.resolutions_per_authority:
136                if resolution.status.code == StatusCode.ER_SUCCESS_MATCH:
137                    for value in resolution.values:
138                       if value.value and value.value.name:
139                            return value.value.name

**Comment by yjp909** [comment]
![lambda_function py](https://user-images.githubusercontent.com/65332296/81956326-c8cda500-9628-11ea-94a5-9cbd36996ad4.PNG)

**Comment by keatontaylor** [comment]
Resolved in VERSION 0.5.3 :)

**Comment by yjp909** [comment]
Thank you so much....Thanks keatontaylor.

**Comment by yjp909** [comment]
Alexa says "There was a problem that the requested skill response". I used Duck DNS URL  : 
 https://name.duckdns.org and in router port forwarded internal 8123 and external 443.
Not using :8123 in URL. Any guidance in this regard, keatontaylor.

**Comment by keatontaylor** [comment]
@yjp909 generally we're trying to keep support of connectivity issues in the [Discord](https://discord.gg/AWgE6g) #alexa-actionable-notifications channel.

**Comment by yjp909** [comment]
ok. Got it. Thank you.

**Comment by JP13090** [comment]
@keatontaylor Is that Discord #Alexa-actionable-notifications section no longer valid?  Invalid link when I click that, but I'm having the same issue.

Expired invite, or I might not have permission to join...

Also using Duck DNS.  https://myuniqueurl.duckdns.org is what I'm pointing it to - no port numbers, etc.

Looking forward to finding this on Discord.  Thanks!
