### ISSUE TITLE
Alexa doesn't ask the command till I say "Alexa, open custom actions".

### ISSUE THREAD

**Issue by ArieDed** [keatontaylor/alexa-actions#30]
Hey,
Really cool addition to Home Assistant and I'm really looking forward to playing around with it. I'm having some trouble though. I've gone through the Alexa developer setup, added the app to my Alexa and am able to run the "Alexa, open custom actions" phrase. But when I run the automation to get the question from Alexa, nothing happens. She only starts asking the question after I say the "Alexa, open custom actions" and after that I can answer yes and the subsequent automation performing the action runs fine. 
I couldn't get access to the Discord server via the links, otherwise I would have asked there, but was hoping I could be helped out with this issue here.

**Comment by rdavey228** [comment]
Have you updated the Alexa Media Player component?

I had the same issue as you and you need to make sure your running the latest version which was updated only a few days ago to support this. Once I replaced all the files in my alexa_media custom component folder with the new ones and restarted HA it worked for me.

**Comment by ArieDed** [comment]
Yes, Alexa Media Player is already updated to the latest version, v2.7.5, using HACS. I'm running Hassio and using a Sonos One as my Alexa.

**Comment by keatontaylor** [comment]
We've had some report that this doesn't appear to be working for them on Alexa enabled Sonos devices.

**Comment by ArieDed** [comment]
Oh, that's a bummer. If you ever need some testing done to maybe get it working on Sonos devices as well, I would be glad to help out.
