### ISSUE TITLE
Echo dot doesn't recognize "open custom actions" command

### ISSUE THREAD

**Issue by zedfour** [keatontaylor/alexa-actions#36]
I've created the skill and successfully enabled/linked the skill in the Alexa app, but the echo won't recognize the command "open custom actions" -- instead it asks about other existing skills with similar names. I've tried changing the Invocation phrase, but similar results. 

In the developer console -> skill -> test tab -- I can test the command "open custom actions" and it replies with text value from the input_text entity from HA. So, the skill and account linking seem to be working. 

In the Alexa app, I've confirmed my Echo dot is listed in devices and communicating back to the app.

Any ideas why this is happening?

**Comment by keatontaylor** [comment]
Make sure that the language you've selected in the skill matches the language that your echos are configured to.

**Comment by zedfour** [comment]
That solved it! 

My device was set to English CA, but the Skill was set to English US. 

I did see your note about the language settings in your setup instructions, but didn't realize the region mattered. 

Thanks for the help.
