### ISSUE TITLE
No answer after media_player.play_media service

### ISSUE THREAD

**Issue by nerdefierodiesserlo** [keatontaylor/alexa-actions#38]
hi guys, i have a problem with the skill...i followed the steps and i added the skill correctly (i guess) but i have some problem when i use the media_player.play_media service inside the script activate_alexa_actionable_notification. I don't get errors but I get no answer from the skill, it is as if the skill does not receive any command. Just to be sure, what is the correct form of HOME_ASSISTANT_URL inide lambda_function.py?
https://mydomain.duckdns.org:443
https://mydomain.duckdns.org
mydomain.duckdns.org

thank you so much for all this awsome work

**Comment by dreimer1986** [comment]
'https://mydomain.duckdns.org' is right. At least here.

**Comment by nerdefierodiesserlo** [comment]
i changed it but no answer...is ther some kind of test to see if the problem is inside the skill? By the way i have an Utterance Conflicts with Dates Durations and Numbers

**Comment by nerdefierodiesserlo** [comment]
ok the test with "alexa, open custom actions" works fine but when i try to run some scripts (and so update the home assistant input_text) the skill remains with the first input_text value, it does not update that. It do it it only If i logout from the alexa app and then i re-link again the skill

**Comment by sp3cialck** [comment]
I'm having the same issue, and can't figure out why... What about you, managed to work?

**Comment by nerdefierodiesserlo** [comment]
nope

**Comment by poudenes** [comment]
Same. command "Open custom Actions" is working. But a script running I get or nothing or the message: "Sorry didn't catch that, none"

**Comment by Didgeridrew** [comment]
I also get nothing but the message: "Sorry didn't catch that, none"
