### ISSUE TITLE
Announce Request

### ISSUE THREAD

**Issue by rul3zz** [keatontaylor/alexa-actions#39]
Hello and tnx for this amazing project!
I have just a question, is possible to use the "announce" sound before the Alexa question?

Oh forgot. The Discord link is not working

**Comment by keatontaylor** [comment]
Yep, I meant to add this far sooner, but the goal is to add the ability to configure a chime before Alexa speaks.

**Comment by dudu631** [comment]
Currently, you can add a SSML audio tag with a chime before the question, and will work fine.

**Comment by maminx** [comment]
Not sure if this goes here, didn't want to open a new issue, since is not an issue, but...
I'm trying to run the script if my Garage stay opened for more than 5 minutes, and I'm triggering the script to multiples alexas, since I have 6, I'm targeting only 3 of them, the thing is, that alexa is asking me if I wan to close my garge door, one at a time, and not simultaneously on the 3 of them.
Is that even possible?
and thanks for this amazing code budy.

**Comment by Bobbyiv** [comment]
@maminx,

This can be done. You have to set up an multiple automation. (You Can also do it in Node red see the first one, "https://github.com/keatontaylor/alexa-actions/wiki/Examples)

This should work to roller over to the next Alexa. You will also have to create an automation for "ResponseNo" and "ResponseYes" if you want them to perform an action.

**Alexa Actionable**
trigger:
  - platform: state
    entity_id: sensor.garage_door
    to: "on"
    for: "00:05:00"
action:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: "I want to close my garage door?"
      event_id: "garage_door_1"
      alexa_device: "media_player.alexa_1"

**First Alexa Response**
trigger:
  - platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: door_1
      event_response_type: ResponseNone
action:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: "I want to close my garage door?"
      event_id: "garage_door_2"
      alexa_device: "media_player.alexa_2"

**Second Alexa Response**
trigger:
  - platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: door_2
      event_response_type: ResponseNone
action:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: "I want to close my garage door?"
      event_id: "garage_door_3"
      alexa_device: "media_player.alexa_3"

**Comment by maminx** [comment]
Nice!, thanks for the tip @Bobbyiv!
