### ISSUE TITLE
"Cannot communicate with Home Assistant"

### ISSUE THREAD

**Issue by cisco187** [keatontaylor/alexa-actions#4]
This is the only message I get at the end of Step two of the configuration.  I linked my HA account using a Nabu Casa URL, so I don't know what's happening.

**Comment by cisco187** [comment]
Got it to work.  Had to make sure there was no trailing forward slash at the end of the NabuCasa URL.

**Comment by keatontaylor** [comment]
I’ll update the wiki. Thank you!

**Comment by jamman9000** [comment]
I'm getting this error today, first attempt at setting this up. I have checked all URLs and everything looks good. Account linking works and I've tried disabling and re-enabling successfully but same error when I ask Alexa to open custom actions. Any clues on where to look? I do have certs, I can reach my HA using my duckdns URL and my firewall is only forwarding 443 to internal 8123. Tried with and without a long-lived access token entered into the lambda_function.py file. Attempted with Verify_SSL true and false (true was with and without token, false was without).

**Comment by jamman9000** [comment]
Well, that's odd. In the setup/configure wiki page it says for the Client Secret "type anything" and I did that for the first attempts, just put in whatever when saving. This time I tossed my long-lived access token into the secret and now it's working. That was with Verify_SLL false, I changed it back to true and it's still working. No token included in the lambda_function file.
