### ISSUE TITLE
Actionable notifications with fire tv cube not working properly

### ISSUE THREAD

**Issue by ikrowni** [keatontaylor/alexa-actions#42]
When using actionable notifications with a fire tv cube it pauses whatever media is playing to show that there is an actionable notification. No matter how i respond to the device no action gets taken. This works fine with my echo dots but the cubes have issues.

**Comment by keatontaylor** [comment]
There are some people saying that echo shows or other devices with displays are not working 100% the same way as the echos. Unfortunately I do not have an fire tv cube or equivalent to test with, but if you can look into the lambda cloud watch logs it might reveal some information that could help.

**Comment by ikrowni** [comment]
Where do I access that and do I just send the logs to you?

**Comment by aolley** [comment]
@keatontaylor 

When I target a dot - logs are generated in cloudwatch. Targetting an echo show - no logs appear at all - which tells me its not even getting to the point of even trying to run the lambda.

**Comment by aolley** [comment]
@keatontaylor 
So I just made it work - the issue for me was that the skill was set to "English (AU)" - however my Show device was set to "English (US)".

Changing the shows language to match the skill, so both were "English (AU)" made it work. I see this is actually noted in your docs.

What I havent tested and might make it easier for a lot of people is to turn on "Sync Locales" for the skill under its language settings - which syncs across the different English variants so the skill supports them all.
