### ISSUE TITLE
Alexa repeats the question the number of entities that are on state to trigger automation 

### ISSUE THREAD

**Issue by laca75tn** [keatontaylor/alexa-actions#44]
It is awesome the work that you have done.  I am very thankful.  I just want you to know.

If you have more than one entity triggering the automation, Alexa asks the question one time per entity that's on the specified state.  For instance, I have 4 lamps in living room.  Any of those lamps triggers the automation, if 3 are on, then Alexa asks three times 'Should I turn the lights off?'.  If two are on, then it does it twice.  This is my automation:

- alias: alexa asks to turn living lights off
  trigger:
    platform: state
    entity_id: 
      - switch.plug_1_relay
      - switch.plug_2_relay
      - switch.plug_3_relay
      - switch.plug_6_relay
    to: 'on'
    for: '00:30:00'

Also, could you have more than one event_response_type?

- alias: 'alexa turns living rooms lights off'
  trigger:
    platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: turn_off_living_room_lights
      event_response_type: 
        - ResponseNone
        - ResponseYes

Thanks again for your hard work!

**Comment by Bobbyiv** [comment]
laca75tn, put all four switches in a group, have the group be your trigger, then if one is on, the group is on and will not mater if you have one on then turn on another.

**Comment by laca75tn** [comment]
> laca75tn, put all four switches in a group, have the group be your trigger, then if one is on, the group is on and will not mater if you have one on then turn on another.
> 
> https://www.home-assistant.io/integrations/group/

Thanks for the solution!  :)
