### ISSUE TITLE
Check if microphone is muted

### ISSUE THREAD

**Issue by seamus65** [keatontaylor/alexa-actions#45]
Not sure if it is an issue or pull request, but I noticed today that if you have the microphone muted she will still ask the question then not hear your response, obviously as the microphone is muted.

I don't know if there is a way to check for microphone muted and do anything about it.

**Comment by keatontaylor** [comment]
I did a little digging and I do not believe this is possible, nor do I think the mute state is exposed anywhere in the unofficial Alexa API that powers alexa media player. 

It looks like this might just be one of those things without a solution and therefore I am unfortunately going to close this issue. If I find out more info I'll resurrect it.

**Comment by seamus65** [comment]
No problem Keaton,
That is what I suspected.
Good work.
