### ISSUE TITLE
ResponseNone do not work on Display Devices currently 

### ISSUE THREAD

**Issue by dudu631** [keatontaylor/alexa-actions#46]
Amazon devices with a Display currently won't trigger ResponseNone events on Alexa Actions, due to the skill remain open on the screen. 

On non-display devices, it's easy to trigger ResponseNone cause you just have to handle the SessionEndedRequest with cause EXCEEDED_MAX_REPROMPTS.

Although on display devices, when the user does not answer a Reprompt the session is not ended (that is the normal behavior according to [this](https://forums.developer.amazon.com/questions/202990/sessionendedrequest-not-fired-for-display-timeout.html) and [this](https://developer.amazon.com/en-US/docs/alexa/custom-skills/display-interface-reference.html#use-of-shouldendsession-attribute-and-session-timeouts)) and it's not possible to handle the "no response" anywhere. Even when the app closes visually, there is no SessionEndedRequest.

I'm currently finding a way to detect the no response on those devices to a question sent - I asked amazon devs and they said they would contact me with a solution or open a feature request on alexa SDK if no solution is possible at the moment. 

Also I opened a [pull request](https://github.com/keatontaylor/alexa-actions/pull/43) to fix wrong ResponseNone events that these devices would trigger on the 2nd attempt on calling it. It only prevents USER_INITIATED wrong event, to push ResponseNone on Home Assistant. That way, Alexa display devices won't trigger oddly a ResponseNone event, and non-display devices won't trigger ResponseNone if you call it twice consecutively by mistake for some reason.

ResponseNone will work fine on non-display devices though.

**Comment by dudu631** [comment]
This is related to issue #17 .

**Comment by keatontaylor** [comment]
Hmm, this is really a shame that amazon is not being consistent in the workflow across devices, especially since SessionEndRequest is intended to allow the lambda code to properly cleanup any state that would otherwise cause issues, even if that is not how it is being used in this custom component.

**Comment by CobraDunn** [comment]
@keatontaylor - Has a solution or workaround been found for this? It prevents cascading through devices for a response.

**Comment by kiragengis** [comment]
Are there any updates about this? I only have Amazon devices with a Display :(

**Comment by mattfacer** [comment]
Has there been any updates on this? Still not working. 
Thanks
