### ISSUE TITLE
Speech Synthesis Markup Language not working

### ISSUE THREAD

**Issue by deonte1threatt** [keatontaylor/alexa-actions#48]
The Speech Synthesis Markup Language (whisper, ETC) causes the alexa device say "There was a problem with the requested skill's response" and then any call to an alexa device after that has no voice. I used the provided example to see if i messed up the syntax but nothing.

**Comment by giovannijoao** [comment]
Hi,

Did you find something more about it? I'm facing the same problem.

**Comment by Flight777** [comment]
Same issue, and no idea how that fix the voice afterwards...

**Comment by DEADSEC-SECURITY** [comment]
Is this still an issue? Could you post log information and any other stuff that might be useful?
