### ISSUE TITLE
[Feature Request] Pass-through to Home Assistant intent scripts

### ISSUE THREAD

**Issue by cerebrate** [keatontaylor/alexa-actions#52]
I've already got fairly extensive Alexa integration for my Home Assistant set up with the built-in Alexa Custom Skill and Smart Home Skill integrations, and I'd prefer to not have to add yet another skill to make use of this. Is it possible to, adding the relevant intents to my existing custom skill, modify the lambda_function.py here to pass unrecognized intents through to Home Assistant in the same way that [the integration's script](https://gist.github.com/lpomfrey/97381cf4316553b03622c665ae3a47da) does?

I've tried hacking on this a little myself, but I can't seem to figure out how to get the raw request information back out of input_handler.

**Comment by ronsum232** [comment]
HA documentation: [https://www.home-assistant.io/integrations/alexa.intent/](url)
Lambda used: [https://gist.github.com/lpomfrey/97381cf4316553b03622c665ae3a47da](url)

Thanks for you awesome work!

**Comment by cerebrate** [comment]
Sorry it took me a while to get back to you on this; I'm using the same HA feature and lambda function as @ronsum232 .

**Comment by DEADSEC-SECURITY** [comment]
Is this still an issue?
