### ISSUE TITLE
“There was a problem with the requested skill’s response” 

### ISSUE THREAD

**Issue by mspace00** [keatontaylor/alexa-actions#57]
I am able to link the skill with my instance of Home Assistant, however "open custom actions" results in the response “There was a problem with the requested skill’s response”. I am using the Nginx plugin in Home Assistant for SSL, and I understand others using DuckDNS are having the same issue. 

Testing via Alexa developers console results in the same response.

Discord invite for support is expired.

**Comment by bwarman** [comment]
I'm in the same boat. Everything says it's linked but I get the same response as you. Using DuckDNS/LetsEncrypt for my SSL cert.

**Comment by renatothome** [comment]
Having the same issue.

**Comment by fevaz** [comment]
I'm have using with Nabu Casa e found same problem.


Estou usando com o Nabu Casa e encontrei o mesmo problema.

**Comment by lakefire** [comment]
I deleted and rebuilt my Alexa Skill and this time I added the two files language_strings.json and prompts.py along with lambda_function.py and requirements.txt and it worked for me.

**Comment by fevaz** [comment]
> I deleted and rebuilt my Alexa Skill and this time I added the two files language_strings.json and prompts.py along with lambda_function.py and requirements.txt and it worked for me.

not work for me!

**Comment by bwarman** [comment]
> I deleted and rebuilt my Alexa Skill and this time I added the two files language_strings.json and prompts.py along with lambda_function.py and requirements.txt and it worked for me.

Worked for me as well. I didn't start over though. I just went into the Alexa Developer Console and created the two new files language_strings.json and prompts.py in the Code tab, in the lambda folder where the lambda_function.py and requirements.txt files exist. I copied and pasted the contents of the respective files from the Github code into the newly created files in the developer console. I saved each file after I created them and then deployed the skill again. Tested and it worked.

Thanks! Obviously theres a bug in the code or the installation instructions but this works to get past the problem for now.

**Comment by CommittotheIndian** [comment]
I can confirm the methods from @lakefire & @bwarman worked for me. I also did not rebuild, I just added the files like @bwarman.

**Comment by mspace00** [comment]
@lakefire Thank you! I can confirm this worked for me as well. I also just added the files like @bwarman and did not delete and start over.

**Comment by mspace00** [comment]
SOLUTION: Add the two files language_strings.json and prompts.py to the lambda folder.

**Comment by fevaz** [comment]
I still continue with the problem, even taking the indicated actions.

Ainda continuo com o problema, mesmo realizando as ações indicadas.

Skill response was marked as failure
Personalizada
Request Identifier: amzn1.echo-api.request.6e5ddd41-612f-4f1e-ae04-909af3f74793

The target Lambda application returned a failure response

**Comment by poudenes** [comment]
Same problem but this is my setup:

```
> Skill Code
    > Lambda
        > lambda_function.py
        > language_strings.json
        > prompts.py
        > requirements.txt
       > utils.py
```

But still get the spoken error message

**Comment by casamontico51** [comment]
if you change the "de" language in language_strings.json for the one you use it stops. the error. At least worked for me in spanish:

`"es": {
	    "ERROR_401": "Parece que no tengo autorización para comunicarme con home assistant. Verifique la vinculación de su cuenta o su token de acceso de larga duración y vuelva a intentarlo.",
		"ERROR_404": "Parece que no puedo encontrar la entidad de texto de entrada. Comprueba que lo has añadido a home assistant e inténtalo de nuevo.",
		"ERROR_400": "No se pudo comunicar con home assistant. Consulte los registros de Amazon CloudWatch en la consola del desarrollador de habilidades personalizadas.",
		"ERROR_ACOUSTIC": "Perdon, no entendi eso... <break time='200ms'/> {}",
		"ERROR_CONFIG": "Lo siento, tengo problemas, verifique su configuración, en la habilidad personalizada y vuelva a intentarlo.",
		"ERROR_SPECIFIC_DATE": "Lo siento, no puedo hacer fechas específicas en este momento, prueba una duración en su lugar, como ... en 5 horas.",
		"HELP_MESSAGE": "Esta habilidad solo debe activarse de forma reactiva mientras se activa a través de home assistant",
		"OKAY": "Okay",
		"SELECTED" : "tu seleccionaste {}",
		"SKILL_NAME": "home assistant custom actions",
		"STOP_MESSAGE": "adios!",
		"WELCOME_MESSAGE": "Bienvenido a {}. El texto de entrada es: {}"`

**Comment by NicolasFerreiraHA** [comment]
> I'm have using with Nabu Casa e found same problem.
> 
> Estou usando com o Nabu Casa e encontrei o mesmo problema.

Conseguiu encontrar alguma solução?
