### ISSUE TITLE
The wiki instructions do not include the new multi language files

### ISSUE THREAD

**Issue by stalakerob** [keatontaylor/alexa-actions#58]
Hi, when following the instructions on how to create the skill for alexa, the instructions do not yet include that there are 2 new files (language_strings.json, prompts.py) that need to be added to the lambda directory in the amazon developer console. Without those files the skill does not work.  It took me quite a while to figure that out.

**Comment by Bobbyiv** [comment]
I made the following changes in Red to the Wiki page.

![image](https://user-images.githubusercontent.com/42158485/91922967-3b789400-ec9d-11ea-8089-69505ffc468b.png)

**Comment by stovedoctor** [comment]
im setting up on another HA I did not notice that on this new set up. I been pulling my hair out because it was not working comparing my other install and noticed nothing different.
untill I just saw the update on the wiki.
might want to add in the instruction that they needs to go in the Lambda directory.
My question is do we need to update setups we did months ago or is this just for a updated version. Im not at the other home to see if it is still working or not,

**Comment by Bobbyiv** [comment]
> My question is do we need to update setups we did months ago or is this just for a updated version. Im not at the other home to see if it is still working or not,

@stovedoctor,

I would, I updated mine to keep up with the changes. Makes for less work when a new fetcher is added.

**Comment by aladin2000** [comment]
Here it is with  french  block ...

**{
	"en": {
	    "ERROR_401": "It looks like I am unauthorized to reach home assistant, please check your account linking or your long lived access token and try again",
		"ERROR_404": "It looks like I may not be able to find the input text entity. Please check that you've added it to home assistant and try again",
		"ERROR_400": "Could not communicate with home assistant. Please check the Amazon CloudWatch logs in the custom skill developer console.",
	    "ERROR_ACOUSTIC": "Sorry I did not catch that... <break time='200ms'/> {}",
		"ERROR_CONFIG": "Sorry, I am having trouble, please check your configuration, in the custom skill and try again.",
		"ERROR_SPECIFIC_DATE": "Sorry, I can not do specific dates right now, try a duration instead, like... in 5 hours",
		"HELP_MESSAGE": "This skill should be only reactively while triggered via home assistant.",
		"OKAY": "Okay",
		"SKILL_NAME": "home assistant custom actions",
		"STOP_MESSAGE": "Goodbye!",
		"SELECTED" : "You selected {}",
		"WELCOME_MESSAGE": "Welcome to {}. Input text is: {}"
	},
	"fr": {
        "ERROR_401": "Il semble que je ne suis pas autorisé à accéder à home assistant, veuillez vérifier l'association de votre compte ou votre jeton d'accès de longue durée et veuillez réessayer",
        "ERROR_404": "Il semble que je ne puisse pas trouver l'entité de texte rentrée. Veuillez vérifier que vous l'avez ajoutée à Home HomeAssistant et veuillez réessayer",
        "ERROR_400": "Impossible de communiquer avec l'assistant personnel. Veuillez vérifier les journaux Amazon CloudWatch dans la console de développement des skills personnalisées.",
        "ERROR_ACOUSTIC": "Désolé, je n'ai pas compris ... <break time = '200ms' /> {}",
        "ERROR_CONFIG": "Désolé, je rencontre des problèmes, veuillez vérifier votre configuration, dans la skill personnalisée et réessayer.",
        "ERROR_SPECIFIC_DATE": "Désolé, je ne peux pas faire de dates spécifiques pour le moment, essayez plutôt une durée, comme ... in 5 hours",
        "HELP_MESSAGE": "Cette skill ne doit être activée que de manière réactive lorsqu'elle est déclenchée via HomeAssistant.",
        "OK": "OK",
        "SKILL_NAME": "actions personnalisées de HomeAssistant",
        "STOP_MESSAGE": "Au revoir!",
        "SELECTED": "Vous avez sélectionné {}",
        "WELCOME_MESSAGE": "Bienvenue dans {}. Le texte entré est: {}"
        },
	"de": {
	    "ERROR_401": "Ich habe scheinbar keine Berechtigungen für die verbindung zu home assistant. Bitte prüfe deinen H A Benutzer oder Access Token.",
		"ERROR_404": "Ich kann kein input text Objekt in home assistant finden. Bitte überprüfe ob du dieses bereits hinzugefügt hast.",
		"ERROR_400": "Ich kann keine Verbindung zum home assistant vornehmen. Bitte prüfe die Amazon CloudWatch logdateien in der Alexa Entwickler Console.",
		"ERROR_ACOUSTIC": "Das habe ich leider nicht verstanden... <break time='200ms'/> {}",
		"ERROR_CONFIG": "Entschuldige, hier ist etwas schief gelaufen. Bitte prüfe deine Konfiugration im custom skill und versuche es erneut.",
		"ERROR_SPECIFIC_DATE": "Ich kann leider noch kein spezifisches Datum verarbeiten. Bitte nutze stattedessen Zeiträume wie beispielsweise... in 5 Stunden.",
		"HELP_MESSAGE": "Dieser Skill sollte nur reaktiv genutzt werden, wenn er via home assistant angestossen wird",
		"OKAY": "Okay",
		"SELECTED" : "Du hast {} gewählt",
		"SKILL_NAME": "home assistant custom actions",
		"STOP_MESSAGE": "Machs gut!",
		"WELCOME_MESSAGE": "Willkommen bei {}. Der input text ist: {}"
	}
}**
