### ISSUE TITLE
Problem with skill Reponse

### ISSUE THREAD

**Issue by SCCMOG** [keatontaylor/alexa-actions#59]
Hi there,

Unfortunately I keep receiving:
"There was a problem with the requested skills response" when opening the skill using "Alexa, open custom actions".
Any idea why that is?

Cheers,
SCCMOG

**Comment by SCCMOG** [comment]
Also: https://discord.gg/AWgE6g is now invalid :/

**Comment by patdemko** [comment]
I just tried integrating this as well and I'm getting the same "There was a problem with the requested skills response" after I say "Alexa, open custom actions".  Everything seemed to go smoothly with the install so not sure what could be causing it.

**Comment by patdemko** [comment]
> I just tried integrating this as well and I'm getting the same "There was a problem with the requested skills response" after I say "Alexa, open custom actions". Everything seemed to go smoothly with the install so not sure what could be causing it.

I missed [this post](https://github.com/keatontaylor/alexa-actions/issues/58) below that explained how to fix it by adding those two files to the directory.

**Comment by Bobbyiv** [comment]
Did you add all three files in the Lambda folder? See issue #58.

**Comment by patdemko** [comment]
> Did you add all three files in the Lambda folder? See issue #58.

Yeah, once I figured out that's what I needed to do it started working.  thx!

**Comment by SCCMOG** [comment]
> Did you add all three files in the Lambda folder? See issue #58.

Solved :) @keatontaylor  could you update the Wiki when you have a min?
