### ISSUE TITLE
Language locale

### ISSUE THREAD

**Issue by sinclairfr** [keatontaylor/alexa-actions#60]
Hi, 
I took a moment to translate the locale for french language. 

I am a french native speaker and I think this will do fine : 

```python
   {
     "fr": {
        "ERROR_401": "Il semble que je ne sois pas autorisé à accéder à l'assistant personnel, veuillez vérifier l'association avec votre compte ou votre jeton d'accès de longue durée et réessayer",
        "ERROR_404": "Il semble que je ne puisse pas trouver l'entité de texte d'entrée. Veuillez vérifier que vous l'avez ajoutée à l'assistant personnel et réessayer",
        "ERROR_400": "Impossible de communiquer avec l'assistant personnel. Veuillez vérifier les journaux Amazon CloudWatch dans la console de développement de vos skill.",
        "ERROR_ACOUSTIC": "Désolé, je n'ai pas compris ... <break time = '200ms' /> {}",
        "ERROR_CONFIG": "Désolé, je rencontre des problèmes, veuillez vérifier votre configuration, dans la skill personnalisée et réessayer.",
        "ERROR_SPECIFIC_DATE": "Désolé, je ne peux pas gérer de dates spécifiques pour le moment, essayez plutôt une durée, comme ... dans 5 heures",
        "HELP_MESSAGE": "Cette skill ne doit être activée que de manière réactive lorsqu'elle est déclenchée via home asssistant.",
        "OKAY": "Okay",
        "SKILL_NAME": "home assistant custom actions",
        "STOP_MESSAGE": "Au revoir!",
        "SELECTED": "Vous avez sélectionné {}",
        "WELCOME_MESSAGE": "Bienvenue dans {}. Le texte d'entrée est: {}"
     }
```

Thanks for your hard work,

**Comment by andreprandina** [comment]
I was having trouble trying im portugues, so i translate it, added and it worked...

`},
	"pt": {
	    "ERROR_401": "Parece que não tenho autorização para entrar em contato com o home assistant, verifique a vinculação de sua conta ou seu token de acesso de longa duração e tente novamente.",
		"ERROR_404": "Parece que não consigo encontrar a entidade de texto de entrada. Verifique se você o adicionou ao home assistant e tente novamente.",
		"ERROR_400": "Não foi possível se comunicar com o home assistant. Verifique os logs do Amazon CloudWatch no console do desenvolvedor de habilidades personalizadas.",
		"ERROR_ACOUSTIC": "Desculpe, eu não entendi... <break time='200ms'/> {}",
		"ERROR_CONFIG": "Desculpe, estou tendo problemas, por favor verifique sua configuração, na sua habilidade customizada e tente novamente.",
		"ERROR_SPECIFIC_DATE": "Não posso definir datas específicas no momento, tente uma duração, como ... em 5 horas.",
		"HELP_MESSAGE": "Esta habilidade só deve ser reativa quando acionada pelo home assistant.",
		"OKAY": "Okay",
		"SELECTED" : "Você selecionou {}",
		"SKILL_NAME": "home assistant custom actions",
		"STOP_MESSAGE": "Até logo!",
		"WELCOME_MESSAGE": "Bem-vindo a {}. O texto de entrada é: {}"
	}`

**Comment by DEADSEC-SECURITY** [comment]
Portuguese and French have been added to the repository.
