### ISSUE TITLE
Error: Invalid client id or redirect uri

### ISSUE THREAD

**Issue by poudenes** [keatontaylor/alexa-actions#66]
Hi All,

I checked everything. My Echo Dot language is US.
I can access my HA setup with https://<domain> on port 443

Client ID: https://pitangui.amazon.com/

But I get always this error:

`Error: Invalid client id or redirect uri`

If I change it with a Long Live Token and disable Account Linking then on my App iOS its working
In the test page on developer console its working

![Schermafbeelding 2020-09-13 om 17 41 46](https://user-images.githubusercontent.com/4399532/93022229-76a58c00-f5e8-11ea-84aa-71ceff1b14d1.png)

On my Alexa Echo Dot I get a error:

`sorry i'm having trouble. please try in a little while`

**Comment by MrSleeps** [comment]
You have your language set as GB.. Try changing the client ID to another URL or change the language..

**Comment by poudenes** [comment]
Since 13 sept I didn't try, but I think I tried that already the language ... will pick this up and try again
