### ISSUE TITLE
Automation not running unless ask alexa

### ISSUE THREAD

**Issue by patraRajesh** [keatontaylor/alexa-actions#67]
Working when ask alexa open custom action.  ' would you like me to on it?' asked by alexa and according to the response light is on. But it will not happen automatically. 

The 1st automation  getting executed 
  - alias: bedroom light 
    trigger:
      platform: state
      entity_id: switch.bedroom_switch
      to: 'on'
      for:
        seconds: 20
    action:
      - service: script.activate_alexa_actionable_notification
        data_template:
          text: ' would you like me to on it?'
          event_id: 'actionable_notification_lock_left_unlocked'
          alexa_device: 'media_player.alexa_media__ra'

### **But 2nd never executed unless I ask alexa open custom actions only 2nd (below) code executed**

  - alias: bedlight via actionable notificaiton
    trigger:
      platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_lock_left_unlocked
        event_response_type: ResponseYes
    action:
      - service: switch.turn_off
        entity_id: switch.bedroom_switch

**Comment by Motive313** [comment]
I'm having a similar issue. Invoking the actionable notification never triggers the dot that it was sent to. If I ask alexa to open custom actions, the sent command will happen.

**Comment by Motive313** [comment]
> I'm having a similar issue. Invoking the actionable notification never triggers the dot that it was sent to. If I ask alexa to open custom actions, the sent command will happen.

Ignore this, It was an Alexa Media Player issue.

**Comment by patraRajesh** [comment]
> > I'm having a similar issue. Invoking the actionable notification never triggers the dot that it was sent to. If I ask alexa to open custom actions, the sent command will happen.
> 
> Ignore this, It was an Alexa Media Player issue.

can u explain ur issue? it might help me to fix

**Comment by patraRajesh** [comment]
is the innvocation "custom actions" is necessary means we can use anything else?

**Comment by Motive313** [comment]
> > > I'm having a similar issue. Invoking the actionable notification never triggers the dot that it was sent to. If I ask alexa to open custom actions, the sent command will happen.
> > 
> > 
> > Ignore this, It was an Alexa Media Player issue.
> 
> can u explain ur issue? it might help me to fix

My Alexa Media Player integration was prompted me for a captcha to activate the connection back to my amazon account. Since the integration wasn't working the call to my echo didn't work because the entity to its media_player no longer existed.

After reactivation, the entity existed again and my automation started working again because I had restored access to the media player.

**Comment by ashoktvm** [comment]
Same issue for me. The event triggers when only I say open custom actions

**Comment by Fazer4463** [comment]
Did anyone find a solution to this? I'm having the same problem, it won't send the notification to the echo dot unless I say open custom actions. I have re-installed Alexa Media Player, just in case but it still won't do it
