### ISSUE TITLE
This

### ISSUE THREAD

**Issue by cagriy** [keatontaylor/alexa-actions#69]
This is very exciting, thank you ! Discord says invite expired btw.

For this setup to work, do I have to open Home Assistant Raspberry PI to Internet ? I can run the Lambda function on my AWS account, in a VPC which has VPN access back to pi (i.e. lambda can talk to pi). However, account linking (or token) based authentication seems to require an over-the-internet call.

If there is a workaround I don't want to open up my home assistant port to the world.

**Comment by keatontaylor** [comment]
Account linking will require internet access to the Home Assistant install, however, you do not technically need account linking and can disable it and instead use a token in the lambda function. Hope that helps.
