### ISSUE TITLE
is it a way to work in spanish

### ISSUE THREAD

**Issue by jonydebu** [keatontaylor/alexa-actions#70]
Hi , works nice in english . Is it posible to make it work in spanish ? Need some help , thanks.

**Comment by salvasacie** [comment]
A mi me funcionó traduciendo al español la parte que esta en alemán del archivo language_strings.json. "de": { …. } por "es": { … }

**Comment by andreprandina** [comment]
I added "pt" in language_strings.json. "pt": { …. } , translated everything, and voilá!

**Comment by aladin2000** [comment]
`{
	"en": {
	    "ERROR_401": "It looks like I am unauthorized to reach home assistant, please check your account linking or your long lived access token and try again",
		"ERROR_404": "It looks like I may not be able to find the input text entity. Please check that you've added it to home assistant and try again",
		"ERROR_400": "Could not communicate with home assistant. Please check the Amazon CloudWatch logs in the custom skill developer console.",
	    "ERROR_ACOUSTIC": "Sorry I did not catch that... <break time='200ms'/> {}",
		"ERROR_CONFIG": "Sorry, I am having trouble, please check your configuration, in the custom skill and try again.",
		"ERROR_SPECIFIC_DATE": "Sorry, I can not do specific dates right now, try a duration instead, like... in 5 hours",
		"HELP_MESSAGE": "This skill should be only reactively while triggered via home assistant.",
		"OKAY": "Okay",
		"SKILL_NAME": "home assistant custom actions",
		"STOP_MESSAGE": "Goodbye!",
		"SELECTED" : "You selected {}",
		"WELCOME_MESSAGE": "Welcome to {}. Input text is: {}"
	},
	"fr": {
        "ERROR_401": "Il semble que je ne suis pas autorisé à accéder à Home Assistant, veuillez vérifier l'association de votre compte ou votre jeton d'accès de longue durée et veuillez réessayer",
        "ERROR_404": "Il semble que je ne puisse pas trouver l'entité de texte rentrée. Veuillez vérifier que vous l'avez ajoutée à Home HomeAssistant et veuillez réessayer",
        "ERROR_400": "Impossible de communiquer avec l'assistant personnel. Veuillez vérifier les journaux Amazon CloudWatch dans la console de développement des skills personnalisées.",
        "ERROR_ACOUSTIC": "Désolé, je n'ai pas compris ... <break time = '200ms' /> {}",
        "ERROR_CONFIG": "Désolé, je rencontre des problèmes, veuillez vérifier votre configuration, dans la skill personnalisée et réessayer.",
        "ERROR_SPECIFIC_DATE": "Désolé, je ne peux pas faire de dates spécifiques pour le moment, essayez plutôt une durée, comme ... in 5 hours",
        "HELP_MESSAGE": "Cette skill ne doit être activée que de manière réactive lorsqu'elle est déclenchée via Home Assistant.",
        "OKAY": "OK",
        "SKILL_NAME": "actions personnalisées de Home Assistant",
        "STOP_MESSAGE": "Au revoir!",
        "SELECTED": "Vous avez sélectionné {}",
        "WELCOME_MESSAGE": "Bienvenue dans {}. Le texte entré est: {}"
    }

}`

**Comment by FranMaverix** [comment]
This is for Spanish.
I have it working in my Skill.

-------------------------------------


{
	"en": {
	    "ERROR_401": "It looks like I am unauthorized to reach home assistant, please check your account linking or your long lived access token and try again",
		"ERROR_404": "It looks like I may not be able to find the input text entity. Please check that you've added it to home assistant and try again",
		"ERROR_400": "Could not communicate with home assistant. Please check the Amazon CloudWatch logs in the custom skill developer console.",
	    "ERROR_ACOUSTIC": "Sorry I did not catch that... <break time='200ms'/> {}",
		"ERROR_CONFIG": "Sorry, I am having trouble, please check your configuration, in the custom skill and try again.",
		"ERROR_SPECIFIC_DATE": "Sorry, I can not do specific dates right now, try a duration instead, like... in 5 hours",
		"HELP_MESSAGE": "This skill should be only reactively while triggered via home assistant.",
		"OKAY": "Okay",
		"SKILL_NAME": "home assistant custom actions",
		"STOP_MESSAGE": "Goodbye!",
		"SELECTED" : "You selected {}",
		"WELCOME_MESSAGE": "Welcome to {}. Input text is: {}"
	},
	"es": {
	    "ERROR_401": "Parece que no estoy autorizada para alcanzar Home assistant. Comprueba los datos de enlace con tu cuenta y prueba otra vez",
		"ERROR_404": "No puedo encontrar el input text entity. Comprueba que lo has añadido a tu Home Assistant y prueba otra vez",
		"ERROR_400": "No me he podido comunicar con home assistant. Revisa los registros de Amazon CloudWatch en la consola de desarrolador de tu Skill",
		"ERROR_ACOUSTIC": "Lo siento, no he entendido eso... <break time='200ms'/> {}",
		"ERROR_CONFIG": "Lo siento, estoy teniendo problemas, comprueba la configuración de tu Skill y prueba otra vez.",
		"ERROR_SPECIFIC_DATE": "Lo siento, no puedo hacer fechas específicas ahora, prueba con una duración, como por ejemplo... en 5 horas.",
		"HELP_MESSAGE": "Esta Skill sólo debería ser activada disparada vía home assitant",
		"OKAY": "Vale",
		"SELECTED" : "Seleccionaste {}",
		"SKILL_NAME": "home assistant custom actions",
		"STOP_MESSAGE": "Hasta Luego!",
		"WELCOME_MESSAGE": "Bienvenido a {}. El texto introducido es: {}"
	}
}

**Comment by DEADSEC-SECURITY** [comment]
These new languages have been added to the repo.
