### ISSUE TITLE
Send an arbitrary command (string) to Alexa, as though I spoke "Alexa, command"

### ISSUE THREAD

**Issue by tunerooster** [keatontaylor/alexa-actions#71]
Hi,

My goal is to have alexa reload firefox every 5 minutes after it times out (i.e., to keep HA dashboard on the screen).  As you likely may know, alexa reverts to displaying it's own thing after so many minutes of inactivity, and my HA dashborad disappears until I ask for it again.

I am wondering if _alexa-actions_ can do this, and if not, am suggesting it as a feature request.

The feature would be:

- **send an arbitrary _command_ (string) to Alexa, as though I spoke "Alexa, _command_"**

Would this be hard to add, or is there a way to do it now?  Or, is anyone aware of this functionality in any other package?  Like "relay-assistant" for Google Assistant, if you are familiar with it...

Thanks!

P.S. I got it working and it is impressive!  But, I got to the _alexa_actionable_notification_ part and am stumped what service to call to send a command to alexa.

**Comment by tunerooster** [comment]
Is there a better place to post this?  No replies here...

Thanks...

**Comment by SteveRMann** [comment]
To the best of my knowledge, there is no way to simulate voice-input the way you describe.  If you find something, PLEASE let me know. I am usually browsing the Home Assistant forums as SteveMann or github as SteveRMann.

I had considered a Rube-Goldberg solution using a Raspberry Pi Zero-W running Alexa Pi as the input to Alexa device and a Wemos D1 Mini as the text-to-speech device. So I would MQTT text to the Wemos which would then "speak" it into the Alexa Pi.

**Comment by dreimer1986** [comment]
If whatever you are planning to do can be put inside a routine you could trigger that one from the custom skill, no need for alexa-actions for that though. Sadly I have no Echo Show to try.

**Comment by SteveRMann** [comment]
Why does it have to be an Echo Show?  Any Echo device should work.
Ironically, the Alexa Skill Builder has such a simulator for testing your skills, so it's definitely do-able.

**Comment by keatontaylor** [comment]
Pretty sure routines can now trigger any command you can speak now, and they can be triggered on a timer, so you should be able to do what you're describing entirely with the Alexa app and routines.

**Comment by tunerooster** [comment]
Keaton, that's great to hear...  I'll try it!

**Comment by tunerooster** [comment]
There does not seem to be a way to schedule every 10 minutes, only once a
day.  Please advise if you know a way!  Thanks...

**Comment by Duke-Box** [comment]
Have you got a solution?
The custom component - Alexa Media Player can do this. 

See this and associated other pages on the wiki
https://github.com/custom-components/alexa_media_player/wiki#run-custom-command

**Comment by keatontaylor** [comment]
I'd certainly stick with using Alexa media player for this. I am going to close this issue as it is well defined with AMP.

**Comment by tunerooster** [comment]
My mistake.  I should have closed it.  Media player works fine now.  I
reported this before it was implemented.  Thank you so much for this VERY
useful feature!
