### ISSUE TITLE
Utterance Conflicts

### ISSUE THREAD

**Issue by Veuchez** [keatontaylor/alexa-actions#73]
I don't know what it is but when I import the json it reports this error.

Utterance Conflicts (1)

Alexa will attempt to disambiguate utterance between custom intents
Date, Duration, Number.

**Comment by Veuchez** [comment]
This error occurs only if I use "italian" as language

**Comment by andreprandina** [comment]
I do have de same issue using "portuguese" (pt-BR)

**Comment by jonydebu** [comment]
Same issue here in "spanish"

**Comment by corgan2222** [comment]
same in german

**Comment by aladin2000** [comment]
> I don't know what it is but when I import the json it reports this error.
> 
> Utterance Conflicts (1)
> 
> Alexa will attempt to disambiguate utterance between custom intents
> Date, Duration, Number.

same for french

**Comment by ahnernoch** [comment]
Also here for german. Skill is not working for me.

**Comment by DEADSEC-SECURITY** [comment]
This repo doesnt't support many languages, if yours isn't supported yet it wont work.
