### ISSUE TITLE
The Test did not work in new HA 

### ISSUE THREAD

**Issue by aladin2000** [keatontaylor/alexa-actions#76]
###  For all support requests it is strongly recommend you join the #alexa-actionable-notifications discord channel for assistance. Myself and others are able to help you in real-time with issues.  [Discord Invite Link](https://discord.gg/AWgE6g)

For all other issues and feature requests, please replace this text with your issue or feature request. Thank you so much for all the support!
I could not get a corredct answer. I am in Home Assistant 2021.2.3

![image](https://user-images.githubusercontent.com/16690723/107974394-d13b7d80-6fb6-11eb-8782-2879dac9e3c4.png)

I think I followed all steps and double checked them....  

remark the discord invitation seems invalid ? 

Any idea

**Comment by Bobbyiv** [comment]
This link is only good for 7 days (2/23//2021).

https://discord.gg/qUErTEz2
