### ISSUE TITLE
at alexa skill crreate _ code step _ lambda_function.py, requirements.txt files are not shown 

### ISSUE THREAD

**Issue by basem99h** [keatontaylor/alexa-actions#77]
###  For all support requests it is strongly recommend you join the #alexa-actionable-notifications discord channel for assistance. Myself and others are able to help you in real-time with issues.  [Discord Invite Link](https://discord.gg/AWgE6g)

during the setup of Alexa skill, and after account linking step, when i went to Code tab, then lambda_function.py, requirements.txt files was not shown, and only shown as the following picture
![image](https://user-images.githubusercontent.com/60322155/108104257-200f1300-709c-11eb-9939-f9d14102fbf9.png)

however, i added all the files manually and copied the codes inside, then deploy

when i tested the skill after i have enabled it  "Alexa , open custom actions" ==> the response was "there is problem in the requested skill response"

anyone can help ?

thanks

**Comment by camillohbrandao** [comment]
it doesn't work for me either. Can anyone help?

**Comment by razorface1978** [comment]
i also have the same problem

**Comment by camillohbrandao** [comment]
Works for me!

You need the external link for access your home assistant, booth copy this archives at your Alexa skill:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/32912271/108835345-1d398400-75ae-11eb-8d96-ed524be6ed2d.png">

**Comment by razorface1978** [comment]
I have checked everything still doesn't work
-------- Original message --------From: camillohbrandao <notifications@github.com> Date: 2/23/21  6:08 AM  (GMT-05:00) To: keatontaylor/alexa-actions <alexa-actions@noreply.github.com> Cc: razorface1978 <razorface1978@comcast.net>, Comment <comment@noreply.github.com> Subject: Re: [keatontaylor/alexa-actions] at alexa skill crreate _ code step _ lambda_function.py, requirements.txt files are not shown  (#77) 
Works for me!
You need the external link for access your home assistant, booth copy this archives at your Alexa skill:

**Comment by willbob8** [comment]
When you create the skill, on the first page when you select custom as the model the second part asks for the 'method to host your skill's backend resources'
Under this, select 'Alexa-Hosted (Python)' (by default it is Node.js)
