### ISSUE TITLE
New dynamic template for sensor.last_alexa

### ISSUE THREAD

**Issue by danielbrunt57** [keatontaylor/alexa-actions#79]
I bungled my actionable notifications just over a week ago.  I spent a lot of time off and on diagnosing the issue which was: a couple of echo's worked but the remaining 5 did not.  Yesterday I finally figured out the problem: I had renamed devices in Alexa but neglected to update the static entity list in group.echos.  Today I lashed together a value_template (based on code gleaned from other sources) that searches the domain media_players for the attribute last_called and if true returns the entity_id so  I now no longer have to worry about maintaining group.echos!
```
sensor:
  - platform: template
    sensors:
      last_alexa:
        value_template: >
            {%- for group in states.media_player | groupby('state') -%}
              {%- for entity in group.list -%}
                {%- if is_state_attr(entity.entity_id, 'last_called', true) %}
                  {{ entity.entity_id }}
                {%- endif -%}
              {%- endfor -%}
            {%- endfor -%}
```

**Comment by toddrob99** [comment]
This is great. My sensor was working fine, but I'm sure I would forget to update the hard-coded list of devices in my template sensor if I got a new echo. Thank you for sharing.
