### ISSUE TITLE
We were unable to link Home Assistant Home at this time

### ISSUE THREAD

**Issue by drthanwho** [keatontaylor/alexa-actions#8]
Hey, 

Could you clarify what the HA URL on the python file is supposed to be like. You mention about port 443 and certs but I'm not sure if I'm supposed to put my url (e.g. https://domain_nane.ddns.net) with a port number or without. And if it's with a port number is it supposed to be 8123 or 443?

I have both of those external ports pointing to the same ports on my internal IP running HA.  

I've tried without and with either of those ports but still getting "unable to link HA" message.

**Comment by keatontaylor** [comment]
Hey @drthanwho. The wiki explains how to set things up using account linking, but if your home assistant installation only accessible via https://domain_nane.ddns.net:8123 then you'll need to modify the TOKEN parameter in the lambda_function.py to include a long lived token you generate your home assistant installation.

If you can access your home assistant install via https://domain_nane.ddns.net then this would be the URL to enter

**Comment by keatontaylor** [comment]
I've also updated the wiki, let me know if it helps.

**Comment by drthanwho** [comment]
This looks like it works now. Thanks! :smile:  

In terms of security though, I assume this only works with Alexa devices that are linked to the account I have created the skill in, right? The skill isn't public to other users?

P.S. there's a typo on the new text (log instead of long) and also one the All Done section (native - I think you meant navigate)

**Comment by keatontaylor** [comment]
Correct only accessible via the echo devices on the same account, and it is not public.

I'll update the wiki to correct the typos. Thanks!

**Comment by ValiEne** [comment]
Guys, what I'm doing wrong? My HA instance is accessible through 8234 TCP port. So the .py script looks like this:
`HOME_ASSISTANT_URL                = 'https://xxx.yyy.me:8234'       # REPLACE WITH THE URL FOR YOUR HA FRONTEND
VERIFY_SSL                        = True                              # SET TO FALSE IF YOU DO NOT HAVE VALID CERTS
TOKEN                             = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUz`
Every time I'm trying to link the Alexa Skill I get an error: "Error: invalid client ID or redirect uri"  and HA notifies me "Login attempt or request with invalid authentication from x.y.z.w"

**Comment by keatontaylor** [comment]
@ValiEne please come join us in the #alexa-actionable-notificaiton chat on [Discord](https://discord.gg/AWgE6g)
