### ISSUE TITLE
Alexa emotions

### ISSUE THREAD

**Issue by reavenm** [keatontaylor/alexa-actions#80]
Having problems using alexa emotions on the notifications. I tried to change double quotes to singles and enclose everything in single quotes but all I get is the echo lighting on and off again, otherwise it works if I just put the text

<amazon:emotion name="excited" intensity="medium"> the garage is still open, you want me to close it? </amazon:emotion>

Using the latest home assistant and the latest available alexa-actions

**Comment by reavenm** [comment]
Any advice?

**Comment by Bobbyiv** [comment]
> Any advice?

See if this video will help. 

https://youtu.be/CWrjPJ8gjKQ

**Comment by danielbrunt57** [comment]
This works:
`text: "<amazon:emotion name='excited' intensity='medium'> the garage is still open, you want me to close it? </amazon:emotion>"`
