### ISSUE TITLE
HA behind Nginx Proxy Manager

### ISSUE THREAD

**Issue by poudenes** [keatontaylor/alexa-actions#81]
Hi All,

I follow the steps very clear. My HA is behind Nginx Proxy Manager
I can connect to HA using:

https://ha.domain.com (Proxy will forward this to 192.168.100.24:8123)

But when do the test I get all the time:

`Sorry I did not catch that... None`

**Comment by stefancvetkovic** [comment]
Have you resolved this?
I have same situation

**Comment by poudenes** [comment]
Yes. I disconnect all skills and after some yours connect them again. that was solving my issue
