### ISSUE TITLE
Wrong Intent?

### ISSUE THREAD

**Issue by bigverm23** [keatontaylor/alexa-actions#82]
I say Alexa, open custom actions...."welcome to the conversation start sample....what's your favorite color"?

I followed the instructions on the wiki, and then followed again...but this is the result I'm getting.  Any help woudl be appreciated.

**Comment by Bobbyiv** [comment]
> I say Alexa, open custom actions...."welcome to the conversation start sample....what's your favorite color"?
> 
> 
> 
> I followed the instructions on the wiki, and then followed again...but this is the result I'm getting.  Any help woudl be appreciated.
> 
> 

Try these two videos for help. They might help find the problem. These videos where done when it first come out, but they should be able to assist. 

https://youtu.be/cCw0vWuhjnY

https://youtu.be/cxAk31EnrY8

**Comment by bigverm23** [comment]
I'm getting closer, but I still cannot get Alexa to say anything once the home assistant device action occurs, in Node Red.

**Comment by Bobbyiv** [comment]
> I'm getting closer, but I still cannot get Alexa to say anything once the home assistant device action occurs, in Node Red.

Did you import the Node Red Flow in the Wiki Examples? This should have every thing you need for the Node Red Flow.

**Comment by bigverm23** [comment]
> > I'm getting closer, but I still cannot get Alexa to say anything once the home assistant device action occurs, in Node Red.
> 
> Did you import the Node Red Flow in the Wiki Examples? This should have every thing you need for the Node Red Flow.

Yes.  I have Alexa Media Player installed and working....and imported the full example direclty into Node Red....I cant figure out what the problem is.  Wiki script is in the yaml as well.

**Comment by Bobbyiv** [comment]
> > > I'm getting closer, but I still cannot get Alexa to say anything once the home assistant device action occurs, in Node Red.
> 
> > 
> 
> > Did you import the Node Red Flow in the Wiki Examples? This should have every thing you need for the Node Red Flow.
> 
> 
> 
> Yes.  I have Alexa Media Player installed and working....and imported the full example direclty into Node Red....I cant figure out what the problem is.  Wiki script is in the yaml as well.

Try this video, it uses the Node Red flow and walks you through using it. Start watching at time stamp 1:08:28. 

https://youtu.be/t7LcUqOcQKc

**Comment by bigverm23** [comment]
here's what I have in the ASK node....never speaks, but you can see it activates the script.  Not sure what I'm missing.
{
    "text": "Garage Door just opened, do you want to close it?",
    "event_id": "actionable_notification_garage_open",
    "alexa_device": "media_player.kitchen_echo"
}

![image](https://user-images.githubusercontent.com/17554438/113145716-c7837780-91fc-11eb-91f9-2e98e9cf6628.png)

**Comment by Bobbyiv** [comment]
> here's what I have in the ASK node....never speaks, but you can see it activates the script. Not sure what I'm missing. I wonder if it's related to the TEXT below....like it just doesnt work in my setup for some reason. BUT the Alexa Actionable Notification Events listener also never gets triggered...idk
> {
> "text": "Garage Door just opened, do you want to close it?",
> "event_id": "actionable_notification_garage_open",
> "alexa_device": "media_player.kitchen_echo"
> }
> 
> ![image](https://user-images.githubusercontent.com/17554438/113145716-c7837780-91fc-11eb-91f9-2e98e9cf6628.png)
> 
> ***What is also interesting is if i say "open custom actions" it runs my automation in Node-Red, regarding the garage door, and works as designed....vs. running the sample.

Sorry, I don't know what the issue is. Did you test the settings before you started the Node Red flows? Did it work?

**Comment by bigverm23** [comment]
after a few attempts I got it to work
