### ISSUE TITLE
Only receiving "ERROR_ACOUSTIC" response

### ISSUE THREAD

**Issue by jgthornburgh** [keatontaylor/alexa-actions#84]
I have everything setup but no matter what I do the YesIntent isn't accepted. In the simulator you can see that alexa see's my response as a YesIntent, but the code outputs the text for "ERROR_ACOUSTIC"

![image](https://user-images.githubusercontent.com/44178327/115313677-91b11f00-a128-11eb-9ad6-b83e702a9616.png)

**Comment by DuncanRae** [comment]
Hi, I'm having exactly the same issue. No matter that I say (yes or no) I get the "Sorry, I didn't catch that" response. Tried different region settings, redone the entire process multiple times.

**Comment by DuncanRae** [comment]
I solved it. I was using a special account on Home Assistant for Alexa linking rather than using my admin account. This seems to be the issue. I gave the Alexa account admin rights on HA, now it's working perfectly.

Hope this helps anyone else having this issue.
