### ISSUE TITLE
Problem when call skill - No prompts module

### ISSUE THREAD

**Issue by nfsilva999** [keatontaylor/alexa-actions#85]
Hi there,
When I try call the skill to test, occurs this error:

[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'prompts'
Traceback (most recent call last):

Any thoughts?

Thanks

**Comment by mendoncart** [comment]
Didn't you forgot to add the prompts.py file and its code to the skill inside alexa console?
