### ISSUE TITLE
Bug Echo show

### ISSUE THREAD

**Issue by niquini** [keatontaylor/alexa-actions#88]
there is a bug on echo show devices that do not support ResponseNone

**Comment by oescafandrista** [comment]
Hi,
I have the same problem!!!!
Have you fixed it?

BR

Ricardo

**Comment by niquini** [comment]
unfortunately no solution to this problem

**Comment by raalsifar** [comment]
Same problem. What Echo Show version do you have? Mine is 5.

**Comment by niquini** [comment]
8

**Comment by aolley** [comment]
Is the issue others are seeing with Echo Show's that the action won't go through at all? Or just that ResponseNone doesn't work?

My echo dot is able to receive an action - but my echo show 8 2nd gen doesn't do anything when it's media_player is targetted.

**Comment by DEADSEC-SECURITY** [comment]
This is currently in the backlog for future development.

**Comment by justinmaiuto** [comment]
I'm finding this same issue, my Echo Show does not support ResponseNone, but other Alexa devices support it fine
