### ISSUE TITLE
TIP for the tutorial

### ISSUE THREAD

**Issue by poudenes** [keatontaylor/alexa-actions#89]
Hi,

After almost 7 months of trying im finally found my issue why it never worked:

```
value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
```

I changed this to:

```
value: "{'text': '{{ text }}', 'event': '{{ event_id }}'}"
```

Because all my yams files have this way of coding...

BUT .... The whole skill is getting broken when I used it. 
After I changed this line back to original it worked great !!!

Maybe you have to add a "Note" to NOT change this line.....

**Comment by DEADSEC-SECURITY** [comment]
Json normally used double quotes so thats why it breaks the skill
