### ISSUE TITLE
Can't get this to work on newer echo devices

### ISSUE THREAD

**Issue by ylduval** [keatontaylor/alexa-actions#9]
I'm not sure if this is related to the created skill or the generation of device. On my 2nd gen amazon echo dot it works as intended as long as I set the location as a US region and US zip code. 
I'm in Canada so I tried changing the region to Canada doesn't work and back to US works.  This is just on the 2nd gen echo dot.

On my 3rd gen echo dot I tried changing this same region but still can't find the command. I also deregistered/reregistered reinstalled skill nothing seems to correct this issue. I'm not sure if I'm missing a setting on the Alexa device side or the Alexa Skill side, but does work on my older echo as longs region is US.

**Comment by keatontaylor** [comment]
I think the issue might be that there are different regions when you create the skill in the Alexa developer kit and so you are only seeing skilsl and skill are only activating if the echo is set to the US region.

**Comment by ylduval** [comment]
Yup! Definitely another region setting somewhere as I created a 2nd skill but using English(US) instead of English(CA) at the start. This corrected the issue, well I should say workaround the issue until I find out where the device specific setting for regions is, as changing it in the Alexa app doesn't work. 
Thank you for your quick reply and great work on this skill, MUCH APPRECIATED. Def. a feature I've been hoping someone would figure out, and you did it! Thank you :) Also another big thanks on the documentation, SUPER EASY and straight forward.
