### ISSUE TITLE
Acknowledge sound as "Okay" ?

### ISSUE THREAD

**Issue by Bl4cksus** [keatontaylor/alexa-actions#96]
Hi,

I'm aware that we are able to change the confirmation response from "Okay" to other words in the language_strings.json - but is there any way to use the usual confirmation sound an Alexa device would make when taking a smart home order?

I would often want an Alexa tts to be part of my HA actions in automations following an actionable Alexa notification , but it would always be prefaced by the "Okay".
An option would be to just make it "" in the language_strings.json, but then there is no confirming sound for automation actions where there isn't a follow up tts. So the regular acknowledge sound would be a perfect middle ground for this.

**Comment by clod986** [comment]
following this thread
