### ISSUE TITLE
Help with actionable notifications! ERROR in logs

### ISSUE THREAD

**Issue by Mattjdlewis** [keatontaylor/alexa-actions#97]
Hi all im having trouble with my actionable notifications, ive set it up following 3 different video's perfectly (DRzZZ) and also the wiki (keatontaylor) ive deployed it and im getting alexa say to me ''there was a problem with the requested skills responce''
I went to CloudWatch Logs and this is the error im getting.

`[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'lambda_function': invalid syntax (lambda_function.py, line 4)
Traceback (most recent call last):
  File "/var/task/lambda_function.py" Line 4
    HOME_ASSISTANT_URL                = ''https://adsadffrvavc4ti4c0e7nxyw0ezkc9abv4q.ui.nabu.casa''      # REPLACE WITH THE URL FOR YOUR HA FRONTEND
`

**Comment by DEADSEC-SECURITY** [comment]
This syntax is wrong: `''https://adsadffrvavc4ti4c0e7nxyw0ezkc9abv4q.ui.nabu.casa''`
Should be: `'https://adsadffrvavc4ti4c0e7nxyw0ezkc9abv4q.ui.nabu.casa'`
