### ISSUE TITLE
Alexa Setup

### ISSUE THREAD

**Issue by yashdeepsharmaa** [keatontaylor/alexa-actions#98]
###  For all support requests it is strongly recommend you join the #alexa-actionable-notifications discord channel for assistance. Myself and others are able to help you in real-time with issues.  [Discord Invite Link](https://discord.gg/AWgE6g)

For all other issues and feature requests, please replace this text with your issue or feature request. Thank you so much for all the support!

**Comment by stackunderflows** [comment]
@yashdeepsharmaa Can you update the discord link? That invite is invalid.

**Comment by danielbrunt57** [comment]
![image](https://user-images.githubusercontent.com/49846893/163164224-ff5a62f9-96b6-4cd6-ba92-d7690944bacf.png)

**Comment by DEADSEC-SECURITY** [comment]
Discord is no longer available as far as I know
