### ISSUE TITLE
Alexa does not respond to custom actions only there was problem

### ISSUE THREAD

**Issue by mrteausa** [keatontaylor/alexa-actions#99]
I have recreate the custom skill several times and using nabu casa url.  I open the Alexa app and the linking works successfully.  When I asked Alexa it stated "There was a problem with the requested skill's response".   I use the Test on Alexa developer console, it respond the same.  Is there any account payment setup issue, I need to check on Amazon?

**Comment by RandomPotato893** [comment]
I have this same problem

**Comment by mccoy7777** [comment]
> I have recreate the custom skill several times and using nabu casa url. I open the Alexa app and the linking works successfully. When I asked Alexa it stated "There was a problem with the requested skill's response". I use the Test on Alexa developer console, it respond the same. Is there any account payment setup issue, I need to check on Amazon?

Did you ever get this issue resolved?

**Comment by mrteausa** [comment]
Yes, it is the configuration yaml file I did not put the input text: alexa_actionable_notification there.  Instead I put on the Helpers file and it does not work there.
Looks like this line is required on the configuration file only.
Thanks for checking.

**Comment by fabHAgithub** [comment]
I didn't understand the context and how you fixed the problem, friend. How is your final file? You can share?

>

**Comment by Riley102** [comment]
i had the same issue, make sure you add the following to you configuration. yaml  file in home assistant then restart you home assistant server.

input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'

**Comment by lidans5** [comment]
same problem over here, using duck-dns
any suggestions?

**Comment by thejeffreystone** [comment]
I haven't got past this one either. Not sure what is going on yet. But it should have any bearing on where the input_text is defined. Mine is in a package file, and when I call the actionable notification script it updates my input text. 

But I cannot get the skill to work properly on the Amazon side.

**Comment by zuldero** [comment]
i just set the whole skill up today. and it worked after a bit of strugle. i had a typo in a file that i needed to creat. at least for me the skill still works

**Comment by drumtrich** [comment]
Same Problem. I recreated the skill several times. Authentication works, but I have response error when open the custom action via alexa.

**Comment by DEADSEC-SECURITY** [comment]
This seems to be fixed, so closing the closing this issue
